"use client";
import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
type Message={id:number;topic:string;message:string;page:string;status:string;email?:string};
export default function HelpPage(){const [topic,setTopic]=useState('Site issue'),[message,setMessage]=useState(''),[page,setPage]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[admin,setAdmin]=useState(false),[messages,setMessages]=useState<Message[]>([]);
 async function refresh(){const r=await fetch('/api/help',{cache:'no-store'}),data=await r.json();if(!r.ok)throw Error(data.error);setAdmin(data.admin);setMessages(data.messages||[]);}
 useEffect(()=>{setPage(new URLSearchParams(window.location.search).get('from')||'');void refresh().catch(e=>setStatus(e.message));},[]);
 async function send(e:FormEvent){e.preventDefault();setBusy(true);setStatus('');try{const r=await fetch('/api/help',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,message,page})}),data=await r.json();if(!r.ok)throw Error(data.error);setMessage('');setStatus(`Message ${data.id} saved for admin review.`);await refresh();}catch(e){setStatus(e instanceof Error?e.message:'Your message could not be saved.');}finally{setBusy(false);}}
 return <main className="help-page"><Link href="/">← TTCGameLab</Link><h1>How can we help?</h1><p>Workshop creates your pieces. Build Space connects them to host controls and the overlay. Test a complete round, then publish when you are ready.</p><div className="help-links"><Link href="/guide">Step-by-step walkthrough</Link><Link href="/reference">Try the practice project</Link><Link href="/projects">Return to my projects</Link></div><section><h2>Contact the admin</h2><p>Report a site issue, share a concern, or suggest an improvement.</p><form onSubmit={send}><label>What is this about?<select value={topic} onChange={e=>setTopic(e.target.value)}>{['Site issue','Concern','Recommendation'].map(t=><option key={t}>{t}</option>)}</select></label><label>Your message<textarea required minLength={5} maxLength={5000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Tell us what happened or what you would like improved."/></label>{page&&<small>Related page: {page}</small>}<button className="build-btn" disabled={busy||message.trim().length<5}>{busy?'Sending…':'Send to admin'}</button><p role="status">{status}</p></form></section><section><h2>{admin?'Admin help inbox':'Your messages'}</h2>{!messages.length&&<p>No messages to show.</p>}{messages.map(m=><article key={m.id}><strong>{m.topic} · {m.status}</strong>{m.email&&<p>{m.email}</p>}<p style={{whiteSpace:'pre-wrap'}}>{m.message}</p>{m.page&&<small>{m.page}</small>}{admin&&<label>Review status<select value={m.status} onChange={async e=>{try{const r=await fetch('/api/help',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:Number(m.id),status:e.target.value})});if(!r.ok)throw Error('Status could not be saved.');await refresh();}catch(e){setStatus(e instanceof Error?e.message:'Update failed.');}}}>{['New','Reviewed','Resolved'].map(s=><option key={s}>{s}</option>)}</select></label>}</article>)}</section></main>;
}
