const assert=require('node:assert/strict'),load=require('./load.cjs');
const {imageLayout,imageAspectRatio}=load('lib/image-layout.ts');
const {checkedAssistantMediaAction}=load('lib/assistant-media-actions.ts');
const portrait=imageLayout(900,1600,{width:1920,height:1080,fit:'contain'});
assert.equal(portrait.drawHeight,1080);assert.equal(portrait.drawWidth,607.5);
assert.equal(portrait.ratio,16/9);
const cropped=imageLayout(900,1600,{width:1920,height:1080,fit:'cover'});
assert.equal(cropped.drawWidth,1920);assert(cropped.drawHeight>1080);
const landscape=imageLayout(1920,1080,{width:1080,height:1920,fit:'contain'});
assert.equal(landscape.drawWidth,1080);assert.equal(landscape.drawHeight,607.5);
assert.equal(imageLayout(900,1600,{crop:'square'}).fit,'cover');
assert.equal(imageLayout(900,1600,{crop:'square',fit:'contain'}).drawWidth,506.25);
assert.equal(imageLayout(900,1600,{width:800}).height,1422);
assert.equal(imageLayout(900,1600,{height:800}).width,450);
assert.equal(imageLayout(900,1600,{width:1234,height:567}).height,567);
assert.equal(imageAspectRatio({width:1920,height:1080}),'16:9');
assert.equal(imageAspectRatio({crop:'portrait'}),'9:16');
assert.equal(imageAspectRatio({}),'auto');
const assets=[{name:'Tall.png',type:'image/png'}];
assert.equal(checkedAssistantMediaAction({type:'render-copy',sourceKey:'Tall.png',edits:{width:1920,height:1080,fit:'contain'}},assets).edits.fit,'contain');
assert.throws(()=>checkedAssistantMediaAction({type:'render-copy',sourceKey:'Tall.png',edits:{fit:'invalid'}},assets));
console.log('PASS: portrait/landscape fit and crop geometry, custom exact sizes, generation shape and validated AI copies.');
