const fs=require('fs'),vm=require('vm'),ts=require('typescript'),assert=require('node:assert/strict'),load=require('./load.cjs');
function harness(){const slots=[],effects=[];let cursor=0;const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return [slots[i],value=>slots[i]=typeof value==='function'?value(slots[i]):value];},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect:(fn,deps)=>{const i=cursor++;if(!slots[i]||deps.some((d,n)=>d!==slots[i][n])){slots[i]=deps;effects.push(fn);}}};
 function module(file,deps={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,require:id=>id==='react'?react:id==='react/jsx-runtime'?require(id):deps[id]||{},Math,Number,Date,setInterval:()=>0,clearInterval(){}});return exports;}
 return {module,render:fn=>{cursor=0;const result=fn();effects.splice(0).forEach(fn=>fn());return result;}};
}
function nodes(n){if(Array.isArray(n))return n.flatMap(nodes);return n&&typeof n==='object'?[n,...[].concat(n.props?.children||[]).flatMap(nodes)]:[];}
const {movePlacement,resizePlacement,toolShapePlacement}=load('lib/overlay-placement.ts');
const p={x:20,y:20,width:30,height:25};const moved=movePlacement(p,100,100);assert.equal(moved.x,70);assert.equal(moved.y,75);assert.equal(moved.width,30);assert.equal(moved.height,25);assert.equal(resizePlacement(p,100,100).width,80);
const circle=toolShapePlacement(p,'circle');assert.equal(circle.width*1920,circle.height*1080);
const drag=harness(),Editor=drag.module('components/YouTubePlacementEditor.tsx',{'../lib/overlay-placement':load('lib/overlay-placement.ts'),'../lib/youtube':load('lib/youtube.ts')}).default;let saved,placement=p;
const render=()=>drag.render(()=>Editor({placement,label:'Timer',onChange:value=>{saved=value;placement=value;}}));let tree=render();assert(!nodes(tree).some(n=>n.props.className==='overlay-size-panel'));
let button=nodes(tree).find(n=>n.props['aria-label']==='Move Timer');const target={setPointerCapture(){},parentElement:{parentElement:{getBoundingClientRect:()=>({width:640,height:360})}}};const event=(x,y)=>({currentTarget:target,clientX:x,clientY:y,pointerId:1,preventDefault(){}});
button.props.onPointerDown(event(100,100));button.props.onPointerMove(event(228,172));button.props.onPointerUp();assert.equal(saved.x,40);assert.equal(saved.y,40);assert.equal(saved.width,30);assert.equal(saved.height,25); // no render between move and release
tree=render();button=nodes(tree).find(n=>n.props['aria-label']==='Move Timer');button.props.onPointerDown(event(100,100));button.props.onPointerMove(event(36,64));button.props.onPointerUp();assert.equal(saved.x,30);assert.equal(saved.y,30);tree=render();assert(nodes(tree).some(n=>n.props['aria-label']==='Move Timer'));assert(nodes(tree).some(n=>n.props['aria-label']==='Resize Timer')); // repeated movement remains available
saved=undefined;tree=render();button=nodes(tree).find(n=>n.props['aria-label']==='Move Timer');button.props.onPointerDown(event(100,100));button.props.onPointerMove(event(400,300));button.props.onPointerCancel();assert.equal(saved,undefined);
const editing=harness(),hook=editing.module('components/useEditableTool.ts'),ToolEditor=editing.module('components/GameToolEditor.tsx',{'./useEditableTool':hook,'../lib/overlay-placement':load('lib/overlay-placement.ts'),'../lib/fonts':load('lib/fonts.ts'),'../lib/tool-style':load('lib/tool-style.ts'),'../lib/game-tools':load('lib/game-tools.ts')}).default;
let tool={id:'timer',name:'Timer',type:'countdown',enabled:true,config:{seconds:135,appearance:{backgroundColor:'#101827'},placement:{x:20,y:20,width:30,height:25}}};const onSave=next=>tool=JSON.parse(JSON.stringify(next));const toolRender=()=>editing.render(()=>ToolEditor({tool,assets:[],project:{controls:[],assets:[],gameTools:[tool]},onSave}));tree=toolRender();let colors=nodes(tree).filter(n=>n.type==='input'&&n.props.type==='color');colors[0].props.onChange({target:{value:'#ff0066'}});colors[1].props.onChange({target:{value:'#00ff88'}});assert.equal(tool.config.appearance.backgroundColor,'#ff0066');assert.equal(tool.config.appearance.textColor,'#00ff88');
tool={...tool,config:{...tool.config,placement:{x:50,y:10,width:40,height:50}}};toolRender();tree=toolRender();colors=nodes(tree).filter(n=>n.type==='input'&&n.props.type==='color');assert.equal(colors[0].props.value,'#ff0066');colors[2].props.onChange({target:{value:'#ffee00'}});assert.equal(tool.config.placement.x,50);assert.equal(tool.config.appearance.backgroundColor,'#ff0066');toolRender();tree=toolRender();nodes(tree).find(n=>n.props['aria-label']==='Tool shape').props.onChange({target:{value:'circle'}});assert.equal(tool.config.appearance.shape,'circle');assert.equal(tool.config.placement.width*1920,tool.config.placement.height*1080);assert.equal(tool.config.appearance.backgroundColor,'#ff0066');
const {toolStyle}=load('lib/tool-style.ts');assert.equal(toolStyle(tool).borderRadius,'50%');assert.equal(toolStyle({...tool,config:{...tool.config,appearance:{shape:'rectangle'}}}).borderRadius,0);
console.log('PASS: drag works immediately, releases latest pointer position without shrinking, cancellation does not save, repeated color edits autosave together, external placement survives color edits, saved shape persists, circles have equal pixel dimensions.');
const cardHarness=harness(),cardHook=cardHarness.module('components/useEditableTool.ts'),CardEditor=cardHarness.module('components/QuestionCardEditor.tsx',{'./useEditableTool':cardHook,'../lib/question-cards':load('lib/question-cards.ts'),'../lib/fonts':load('lib/fonts.ts'),'./YouTubePlacementEditor':{default:Editor}}).default;
let card={id:'card',type:'blank-card',name:'Card',enabled:true,config:{text:'Hello'}};const cardSave=next=>card=JSON.parse(JSON.stringify(next));const cardRender=()=>cardHarness.render(()=>CardEditor({tool:card,project:{assets:[],gameTools:[card]},onSave:cardSave}));const content=n=>typeof n==='string'||typeof n==='number'?String(n):[].concat(n?.props?.children||[]).map(content).join('');tree=cardRender();nodes(tree).find(n=>n.type==='button'&&content(n)==='2Look').props.onClick();tree=cardRender();colors=nodes(tree).filter(n=>n.type==='input'&&n.props.type==='color');colors[0].props.onChange({target:{value:'#123456'}});colors[1].props.onChange({target:{value:'#abcdef'}});assert.equal(card.config.questionCard.backgroundColor,'#123456');assert.equal(card.config.questionCard.textColor,'#abcdef');cardRender();tree=cardRender();nodes(tree).find(n=>n.type==='button'&&content(n)==='3Size & position').props.onClick();tree=cardRender();nodes(tree).find(n=>n.type===Editor).props.onChange({x:0,y:40,width:50,height:25});assert.equal(card.config.questionCard.x,0);assert.equal(card.config.questionCard.marginLeft,0);assert.equal(card.config.questionCard.backgroundColor,'#123456');
console.log('PASS: card designer autosaves consecutive color choices, exposes drag handles in Size & position, and saves edge placement without losing the chosen look.');

const timerHarness=harness(),display=timerHarness.module('components/QuestionCards.tsx',{'../lib/question-cards':load('lib/question-cards.ts'),'../lib/game-tools':load('lib/game-tools.ts'),'../lib/fonts':load('lib/fonts.ts'),'../lib/tool-style':load('lib/tool-style.ts')}),runtimeView=timerHarness.module('components/RuntimeActionLayers.tsx',{'../lib/game-tools':load('lib/game-tools.ts'),'../lib/tool-style':load('lib/tool-style.ts'),'./QuestionCards':display,'./CompositionPlayer':{defaultOverlayResult:{x:15,y:20,width:70,height:60}},'./GameToolEditor':load('lib/tool-style.ts')});
const timerTool={id:'timer',name:'Timer',type:'countdown',enabled:true,config:{seconds:135,display:'numbers-bar',appearance:{imageKey:'poster',backgroundColor:'#123456',textColor:'#abcdef',shape:'circle'}}};const preview=runtimeView.ControlAppearancePreview({project:{slug:'test',gameTools:[timerTool],assets:[{storageKey:'poster',url:'https://example.test/poster.png',name:'Poster'}]},control:{id:'show',label:'Show Timer',action:'timer.show.timer',toolIds:['timer']}});const run=timerHarness.render(()=>preview.props.children.type(preview.props.children.props));assert.equal(run.type,display.StyledTimer);const painted=run.type(run.props);assert(nodes(painted).some(n=>n.props.role==='timer'&&n.props.children===135));assert(!nodes(painted).some(n=>n.type==='img'));assert.equal(painted.props.style.background,'#123456');assert.equal(painted.props.style.color,'#abcdef');assert.equal(painted.props.style.borderRadius,'50%');assert(nodes(painted).some(n=>n.props.className==='countdown-bar'));
console.log('PASS: actual timer preview renders countdown numbers and selected bar style with saved colors/shape; an artwork selection cannot replace the timer with a scrolling poster.');
