const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),ts=require('typescript');
const output=ts.transpileModule(fs.readFileSync('lib/question-cards.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const lists={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/card-lists.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:lists,crypto:require('node:crypto').webcrypto,Uint32Array});
const exported={};vm.runInNewContext(output,{exports:exported,require:()=>lists,crypto:require('node:crypto').webcrypto,Date,Math,Set});
const {createCardSystem,freshCardState,cardTransition,cardPhase,publicCardState,questionPool}=exported;
let p={id:'test',gameTools:[{id:'pool',type:'trivia-list',enabled:true,config:{questions:[{question:'First question?',answer:'First answer'},{question:'Second question?',answer:'Second answer'},{prompt:'First question?',answer:'Duplicate must not repeat'}]}}],controls:[]};
p=createCardSystem(p);const tool=p.gameTools.find(t=>t.type==='question-card');
assert.equal('turnTimerId' in tool.config,false);assert.equal('stealTimerId' in tool.config,false);
assert.equal(questionPool(p,tool).length,2);let state=freshCardState();state=cardTransition(p,tool,state,'show',1000,()=>.8);assert.equal(state.question.answer,'Second answer');assert.equal('turnAt' in state,false);assert.equal('stealAt' in state,false);assert.equal(publicCardState(p,tool,state,1000).question.answer,'');
assert.throws(()=>cardTransition(p,tool,state,'show',1000),/Finish or clear/);
assert.equal(cardPhase(p,tool,state,1000000),'question');assert.equal(publicCardState(p,tool,state,1000000).question.answer,'');
assert.throws(()=>cardTransition(p,tool,state,'turn',5000),/Invalid card action/);assert.throws(()=>cardTransition(p,tool,state,'steal',5000),/Invalid card action/);
state=cardTransition(p,tool,state,'reveal',12000);assert.equal(cardPhase(p,tool,state,12000),'answer');
const reloaded=JSON.parse(JSON.stringify(state));state=cardTransition(p,tool,reloaded,'show',13000,()=>.8);assert.equal(state.question.answer,'First answer');assert.equal(state.used.length,2);assert.equal('turnAt' in state,false);assert.equal('stealAt' in state,false);state=cardTransition(p,tool,state,'reveal',14000);assert.equal(cardPhase(p,tool,state,14000),'answer');assert.throws(()=>cardTransition(p,tool,state,'show',15000),/No unused/);
state=cardTransition(p,tool,state,'new-game',16000);assert.equal(state.used.length,0);assert.equal(cardPhase(p,tool,state,16000),'hidden');state=cardTransition(p,tool,state,'show',17000,()=>0);assert.equal(state.question.answer,'First answer');
const b=createCardSystem(p,undefined,'blank');const blank=b.gameTools.find(t=>t.type==='blank-card');let bs=cardTransition(b,blank,freshCardState(),'blank',1000,Math.random,'Private text');assert.equal(bs.blankText,'Private text');assert.equal(cardPhase(b,blank,bs,1000),'question');bs=cardTransition(b,blank,bs,'clear',2000);assert.equal(cardPhase(b,blank,bs,2000),'hidden');
console.log('PASS: paired answers, random unused draw, no repeats after reload, timer-free manual reveal, exhaustion, explicit game reset and blank cards.');
