const assert=require('node:assert/strict'),{groundedResearchCards}=require('./load.cjs')('lib/research-cards.ts');
const evidence=[{url:'https://example.com',title:'Instrument source',summary:'A standard violin has four strings. They are tuned G, D, A and E.'}];
const changes={newTools:[{type:'card-list',config:{cards:[{text:'Invented embellishment',sourceUrl:evidence[0].url,sourceQuote:'A standard violin has four strings.'}]}}]};
const grounded=groundedResearchCards(changes,evidence).newTools[0].config.entries[0];
assert.equal(changes.newTools[0].config.cards.length,0);
assert.equal(grounded.text,'A standard violin has four strings.');assert.equal(grounded.sourceTitle,'Instrument source');
assert.throws(()=>groundedResearchCards({newTools:[{type:'card-list',config:{cards:[{sourceUrl:evidence[0].url,sourceQuote:'A piano contains 12 million parts.'}]}}]},evidence),/copied exactly/);
assert.throws(()=>groundedResearchCards({newTools:[{type:'card-list',config:{cards:[{sourceUrl:'https://invented.example',sourceQuote:evidence[0].summary}]}}]},evidence),/copied exactly/);
console.log('PASS: researched pools reject fabricated links and unsupported details; saved card text comes from its actual source excerpt.');
const {applyBuildChanges}=require('./load.cjs')('lib/build-edits.ts');
const {listCards,savedListEntries,pickerCards}=require('./load.cjs')('lib/card-lists.ts');
const project={id:'research-test',assets:[],gameTools:[],controls:[],overlay:{}};
const saved=applyBuildChanges(project,changes).project;
const pool=saved.gameTools[0];
assert.equal(savedListEntries(pool).length,1);assert.equal(listCards(pool).length,0);assert.equal(saved.controls.length,0);
assert.equal(pickerCards(saved,{config:{listId:pool.id}}).length,0);
const created=applyBuildChanges(saved,{gameTools:[{id:pool.id,config:{makeCardsFromEntries:true}}]}).project;
assert.equal(listCards(created.gameTools[0]).length,1);assert.equal(savedListEntries(created.gameTools[0]).length,1);
assert.equal(listCards(created.gameTools[0])[0].sourceUrl,evidence[0].url);
assert.equal(listCards(saved.gameTools[0]).length,0);
console.log('PASS: saving research creates only pool entries; a later explicit choice creates cards and retains sources.');

const replacement={newTools:[{type:'card-list',name:'Instrument Facts',config:{entries:[{text:evidence[0].summary,sourceUrl:evidence[0].url,sourceQuote:evidence[0].summary}]}}]};
groundedResearchCards(replacement,evidence,[{id:'saved-pool',type:'card-list',name:'Instrument Facts'}],'Replace the existing Instrument Facts pool');
assert.equal(replacement.newTools.length,0);assert.equal(replacement.gameTools[0].id,'saved-pool');assert.equal(replacement.gameTools[0].config.cards.length,0);
console.log('PASS: an explicit pool replacement updates its saved ID rather than creating a duplicate.');
