const assert=require('node:assert/strict'),load=require('./load.cjs'),{addReviewedButtons}=load('lib/reviewed-buttons.ts'),{addCreationControl}=load('lib/build-controls.ts');
const project={id:'review',assets:[{name:'Logo',storageKey:'logo',type:'image/png',url:'https://example.com/logo.png'}],gameTools:[],compositions:[],controls:[{id:'existing',action:'kept',label:'My existing button',appearance:{color:'#ff00ff'}}]};
const preview=addCreationControl(project,'asset','logo');assert.equal(project.controls.length,1);const hide=preview.project.controls.find(c=>c.action.startsWith('result.hide.'));
let result=addReviewedButtons(project,'asset','logo',[{action:'asset.show.logo',label:'Reveal logo'},{action:hide.action,label:'Remove logo'}]);assert.equal(result.project.controls.length,3);const show=result.project.controls.find(c=>c.action==='asset.show.logo'),clear=result.project.controls.find(c=>c.label==='Remove logo');assert.equal(clear.action,'result.hide.'+show.id);assert.equal(show.label,'Reveal logo');assert.deepEqual(result.project.controls[0],project.controls[0]);
result=addReviewedButtons(result.project,'asset','logo',[{action:'asset.show.logo',label:'Other name'}]);assert.equal(result.project.controls.length,3);assert.equal(result.project.controls.find(c=>c.id===show.id).label,'Reveal logo');
result=addReviewedButtons(project,'asset','logo',[{action:'asset.show.logo',label:'Only show'}]);assert.equal(result.project.controls.length,2);assert(!result.project.controls.some(c=>c.action.startsWith('result.hide.')));
console.log('PASS: button preview leaves project unchanged; confirmed labels and optional buttons are applied; Hide targets the actual new Show button; existing controls and appearance are preserved; repeated additions do not duplicate controls.');
const timer={id:'timer',type:'countdown',name:'Answer timer',enabled:true,config:{seconds:45}},timerProject={...project,gameTools:[timer]};const timerPreview=addCreationControl(timerProject,'tool','timer');assert.equal(timerPreview.project.controls.filter(c=>c.toolIds?.includes('timer')).length,4);const timerResult=addReviewedButtons(timerProject,'tool','timer',[{action:'timer.show.timer',label:'Show answer clock'},{action:'timer.toggle.timer',label:'Start or pause clock'}]);assert.equal(timerResult.project.controls.filter(c=>c.toolIds?.includes('timer')).length,2);assert(timerResult.project.controls.find(c=>c.action==='timer.show.timer').detail.includes('without starting'));assert.equal(timerResult.project.gameTools[0].config.seconds,45);console.log('PASS: timer buttons separately show, start/pause, reset and hide; review can keep just the desired actions without changing duration.');
const fs=require('fs'),vm=require('vm'),ts=require('typescript'),{JSDOM}=require('jsdom');const dom=new JSDOM('<!doctype html><main id="root"></main>');global.window=dom.window;global.document=dom.window.document;global.IS_REACT_ACT_ENVIRONMENT=true;const React=require('react'),{createRoot}=require('react-dom/client'),exportsObject={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('components/DashboardButtonReview.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports:exportsObject,require:id=>require(id)});const Review=exportsObject.default,root=createRoot(document.getElementById('root'));let added=[],cancelled=false;const candidates=preview.project.controls.filter(c=>c.id!=='existing');(async()=>{await React.act(async()=>root.render(React.createElement(Review,{name:'Logo',controls:candidates,existingIds:new Set(),onAdd:choices=>added.push(choices),onCancel:()=>cancelled=true})));assert.equal(added.length,0);const inputs=document.querySelectorAll('input:not([type=checkbox])');await React.act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(inputs[0],'Show my logo');inputs[0].dispatchEvent(new dom.window.Event('input',{bubbles:true}));document.querySelectorAll('input[type=checkbox]')[1].click();});assert.equal(added.length,0);await React.act(async()=>[...document.querySelectorAll('button')].find(b=>b.textContent==='Add selected buttons').click());assert.equal(added[0].length,1);assert.equal(added[0][0].label,'Show my logo');await React.act(async()=>[...document.querySelectorAll('button')].find(b=>b.textContent==='Cancel').click());assert(cancelled);await React.act(async()=>root.unmount());console.log('PASS: actual review DOM allows button selection and renaming before confirmation, leaves additions untouched during editing, and exposes cancellation.');})().catch(e=>{console.error(e);process.exitCode=1;});
