const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),ts=require('typescript'),load=require('./load.cjs');
const timerControls=load('lib/timer-controls.ts');
const coins=load('lib/coin-cycle.ts'),chances=load('lib/coin-toss.ts'),connections=load('lib/control-connections.ts');
const control={id:'coin-button',label:'Coin',action:'timer.show.coin',toolIds:['coin']};
const project={id:'test',assets:[],controls:[control],gameTools:[{id:'coin',name:'Coin',type:'countdown',enabled:true,inToolbox:true,config:{triggerOnly:true,seconds:135}}],overlay:{}};
function runtime(){const slots=[];let cursor=0;const exports={};const react={useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=initial;return [slots[i],value=>{slots[i]=typeof value==='function'?value(slots[i]):value;}];},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect(){},useCallback:fn=>fn};
 const dependencies={'../lib/timer-controls':timerControls,'../lib/question-cards':load('lib/question-cards.ts'),'../lib/coin-cycle':coins,'../lib/coin-toss':chances,'../lib/control-connections':connections};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('components/RuntimeActionLayers.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,require:id=>id==='react'?react:id==='react/jsx-runtime'?require(id):dependencies[id]||{},crypto:require('node:crypto').webcrypto,setTimeout,clearTimeout,Date,Math,Uint32Array});
 return ()=>{cursor=0;return exports.useRuntimeActions(project);};}
const render=runtime();render().fire(control);assert.equal(render().runs[0].timerState.running,false);assert.equal(render().runs[0].timerState.remaining,135);render().fire(control);assert.equal(render().runs[0].timerState.remaining,135);render().fire({...control,action:'timer.toggle.coin'});assert.equal(render().runs[0].timerState.running,true);render().fire({...control,action:'timer.toggle.coin'});assert.equal(render().runs[0].timerState.running,false);render().fire({...control,action:'timer.reset.coin'});assert.equal(render().runs[0].timerState.remaining,135);render().fire({...control,action:'timer.hide.coin'});assert.equal(render().runs.length,0);
const a=runtime(),b=runtime();const saved={visible:true,running:false,remaining:95,at:Date.now()};for(const r of [a,b])r().fire(control,{coin:{result:'',timer:saved}});assert.deepEqual(a().runs[0].timerState,b().runs[0].timerState);assert.equal(a().runs[0].timerState.remaining,95);
console.log('PASS: actual runtime shows a stopped timer, repeated Show does not start/reset it, separate start/pause/reset/hide work, server state is identical across overlays.');
