const assert=require('node:assert/strict'),load=require('./load.cjs');
const {cardTransition,freshCardState}=load('lib/question-cards.ts');
const {pickerCards}=load('lib/card-lists.ts');
const {applyBuildChanges}=load('lib/build-edits.ts');
const {controlLabel}=load('lib/game-tools.ts');
const project={id:'test',theme:'cyan',overlay:{title:'Game'},assets:[{storageKey:'a',name:'First',type:'image',url:'/a.svg'},{storageKey:'b',name:'Second',type:'image',url:'/b.svg'},{storageKey:'v',name:'Video',type:'video',url:'/v.mp4'}],assetPools:[{id:'pictures',name:'Pictures',assetKeys:['a','b','v']}],gameTools:[{id:'picker',name:'Pictures',type:'random-picker',enabled:true,config:{source:'images',assetPoolId:'pictures'}}],controls:[],publishedSnapshot:{marker:'unchanged'}};
const picker=project.gameTools[0];
assert.equal(pickerCards(project,picker).length,2);
let state=cardTransition(project,picker,freshCardState(),'toggle',1,()=>0);
assert.equal(state.selectedAssetKey,'a');assert.equal(state.used.length,1);assert.equal(state.cleared,false);
assert.throws(()=>cardTransition(project,picker,state,'draw'),/Remove the current/);
state=cardTransition(project,picker,state,'toggle',2);assert.equal(state.cleared,true);
state=cardTransition(project,picker,JSON.parse(JSON.stringify(state)),'toggle',3,()=>0);
assert.equal(state.selectedAssetKey,'b');assert.equal(state.used.length,2);
state=cardTransition(project,picker,state,'toggle',4);
assert.throws(()=>cardTransition(project,picker,state,'toggle',5),/No unused images/);
state=cardTransition(project,picker,state,'new-game',6);assert.equal(state.used.length,0);
const score={id:'scores',name:'Scores',type:'scoreboard',config:{entries:[{id:'one',name:'Team One',score:5}]}};
let scores=cardTransition(project,score,freshCardState(),'score',1,()=>0,JSON.stringify({id:'one',delta:3}));assert.equal(scores.scores.one,8);
scores=cardTransition(project,score,scores,'toggle');assert.equal(scores.cleared,false);
scores=cardTransition(project,score,scores,'clear');assert.equal(scores.scores.one,8);
scores=cardTransition(project,score,scores,'new-game');assert.equal(scores.scores,undefined);
assert.throws(()=>cardTransition(project,score,scores,'score',1,()=>0,'{"id":"missing","delta":1}'),/Choose an entry/);
const prizes={id:'prizes',name:'Prizes',type:'prize-list',config:{entries:[{id:'p',name:'Prize'}]}};
let awards=cardTransition(project,prizes,freshCardState(),'award',1,()=>0,'{"id":"p","recipient":"Alex"}');assert.equal(awards.awarded.p,'Alex');
assert.throws(()=>cardTransition(project,prizes,awards,'award',2,()=>0,'{"id":"p","recipient":"Another"}'),/already been awarded/);
const changed=applyBuildChanges(project,{connections:[{kind:'tool',id:'picker'}],assets:[{storageKey:'a',edits:{placement:{x:100,y:100,width:40,height:40}}}],newTools:[{type:'scoreboard',name:'Scores',config:score.config,connect:true}]});
assert.equal(changed.warnings.length,0);assert.equal(changed.project.controls.filter(c=>c.action==='cards.toggle.picker').length,1);
assert.equal(controlLabel(changed.project,changed.project.controls.find(c=>c.action==='cards.toggle.picker'),{picker:{cleared:false}}),'Remove image');
assert(changed.project.assets[0].edits.placement.width>0);assert(changed.project.assets[0].edits.placement.height>0);
assert.equal(changed.project.publishedSnapshot,project.publishedSnapshot);assert.equal(project.controls.length,0);assert.equal(project.assets[0].edits,undefined);
const again=applyBuildChanges(changed.project,{connections:[{kind:'tool',id:'picker'}]});assert.equal(again.project.controls.length,changed.project.controls.length);
assert.equal(applyBuildChanges(project,{connections:[{kind:'asset',id:'missing'}]}).warnings.length,1);
console.log('PASS: single random image draw/remove, image-only pool, no repeats after reload, explicit reset, scores and prizes persist until reset, AI connections are idempotent, placements stay visible, live snapshot stays unchanged.');
