"use client";

import Link from "next/link";
import { useState } from "react";

const projects = [
  { id: "haunted-gaming", name: "Haunted Gaming", status: "Published", time: "12 min ago", icon: "👻", accent: "cyan", description: "Spooky alerts, reactive character and horror effects." },
  { id: "space-battle", name: "Space Battle", status: "Published", time: "Yesterday", icon: "🚀", accent: "purple", description: "Futuristic battles with interactive audience events." },
  { id: "christmas-giveaway", name: "Christmas Giveaway", status: "Draft", time: "Dec 18", icon: "🎄", accent: "pink", description: "Festive scenes, giveaways and animated alerts." },
];

export default function Home() {
  const [query, setQuery] = useState("");
  return <main className="shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><span>TT</span></div><div><strong>TTCGameLab</strong><small>LIVE CREATIVE STUDIO</small></div></div><Link href="/project/new" className="new-project"><span>＋</span> New Project</Link><nav><div className="nav-label">WORKSPACE</div><Link href="/" className="nav-item active"><span>⌂</span> Home</Link><Link href="/projects" className="nav-item"><span>▣</span> My Projects <b>3</b></Link><Link href="/assets" className="nav-item"><span>✦</span> Asset Library</Link></nav><div className="sidebar-bottom"><div className="status"><i /> AI Engine Ready</div><div className="profile"><div className="avatar">JT</div><div><strong>Creator</strong><small>Personal workspace</small></div><span>•••</span></div></div></aside>
    <section className="main"><header className="topbar"><div className="crumb"><span>Workspace</span><em>/</em><strong>Home</strong></div><div className="top-actions"><Link className="help" href="/tutorial" aria-label="How to use TTCGameLab" title="How to use TTCGameLab">?</Link><button className="profile-mini">JT</button></div></header><div className="content">
      <section style={{marginBottom:26,padding:20,border:"1px solid #7b4cff",borderRadius:18,background:"rgba(12,8,28,.86)",boxShadow:"0 0 32px rgba(123,76,255,.28)"}}>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:16,marginBottom:14}}>
          <div><strong style={{fontSize:18}}>TTCGameLab Video Walkthrough</strong><div style={{fontSize:13,opacity:.72,marginTop:4}}>Upload the tutorial MP4 here, then watch it with normal video controls.</div></div>
          <label style={{cursor:"pointer",padding:"10px 14px",borderRadius:10,border:"1px solid #ff3dbb",fontWeight:700}}>＋ Upload MP4<input id="tutorial-upload" type="file" accept="video/mp4" style={{display:"none"}} /></label>
        </div>
        <video id="tutorial-player" controls playsInline preload="metadata" style={{display:"none",width:"100%",aspectRatio:"16/9",borderRadius:14,background:"#000"}} />
        <div id="tutorial-empty" style={{display:"grid",placeItems:"center",minHeight:190,border:"1px dashed rgba(255,255,255,.18)",borderRadius:14,opacity:.7}}>Upload the rendered TTCGameLab tutorial to play it here.</div>
        <script dangerouslySetInnerHTML={{__html:`document.addEventListener("change",async function(e){var input=e.target;if(!(input instanceof HTMLInputElement)||input.id!=="tutorial-upload"||!input.files||!input.files[0])return;var file=input.files[0];var fd=new FormData();fd.append("file",file);fd.append("projectId","site-tutorial");var label=input.parentElement;var prior=label&&label.textContent;if(label)label.firstChild.textContent="Uploading…";try{var res=await fetch("/api/assets",{method:"POST",body:fd});var data=await res.json();if(!res.ok)throw new Error(data.error||"Upload failed");localStorage.setItem("ttcgamelab-tutorial-url",data.url);var v=document.getElementById("tutorial-player");var empty=document.getElementById("tutorial-empty");if(v){v.src=data.url;v.style.display="block";v.load();}if(empty)empty.style.display="none";if(label)label.firstChild.textContent="Replace MP4";}catch(err){alert(err instanceof Error?err.message:"Upload failed");if(label)label.firstChild.textContent=prior||"＋ Upload MP4";}});document.addEventListener("DOMContentLoaded",function(){var url=localStorage.getItem("ttcgamelab-tutorial-url");if(!url)return;var v=document.getElementById("tutorial-player");var empty=document.getElementById("tutorial-empty");if(v){v.src=url;v.style.display="block";}if(empty)empty.style.display="none";});`}} />
      </section>
      <section className="hero"><div className="eyebrow"><span className="spark">✦</span> AI-POWERED LIVESTREAM CREATION</div><h1>What are we <span>creating?</span></h1><p>Describe your TikTok LIVE experience. TTCGameLab builds the working dashboard, overlay, interactions, and visuals.</p><div className="prompt-wrap"><textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Tell me what you want to create...\n\nTry: “Create a spooky gaming overlay where my character reacts when someone follows.”'}/><div className="prompt-footer"><div className="prompt-tools"><button>＋ Upload</button><button>◈ Add assets</button></div><Link href={query.trim() ? `/project/new?idea=${encodeURIComponent(query)}` : "/project/new"} className="build-btn">Build with AI <span>→</span></Link></div></div><div className="suggestions"><span>Try one of these:</span><button onClick={()=>setQuery("Create a futuristic space battle stream")}>🚀 Space battle</button><button onClick={()=>setQuery("Create a spooky horror gaming overlay")}>👻 Horror gaming</button><button onClick={()=>setQuery("Create a neon cyberpunk stream")}>⚡ Cyberpunk</button></div></section>
      <section className="projects-section"><div className="section-head"><div><h2>Your projects</h2><p>Pick up where you left off.</p></div><Link href="/projects">View all <span>→</span></Link></div><div className="project-grid">{projects.map(p=><Link href={`/project/${p.id}`} className="project-card" key={p.id}><div className={`preview ${p.accent}`}><div className="preview-grid"/><div className="preview-title">{p.icon} {p.name}</div><div className="preview-center"><span>LIVE</span><strong>YOUR STREAM</strong></div><div className="preview-bar"><i/><i/><i/><i/></div></div><div className="card-body"><div><h3>{p.name}</h3><p>{p.description}</p></div><span className="dots">•••</span></div><div className="card-meta"><span className="published"><i/> {p.status}</span><span>{p.time}</span></div></Link>)}<Link href="/project/new" className="add-card"><div className="add-icon">＋</div><strong>Create a new project</strong><span>Start from a blank canvas</span></Link></div></section>
    </div></section>
  </main>;
}
