"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AssetComposition, CompositionClip, CompositionTrackType, ProjectAsset } from "../lib/project";

const TRACKS: {type:CompositionTrackType;label:string;icon:string}[] = [
  {type:"video",label:"VIDEO",icon:"▣"},{type:"visual",label:"VISUAL",icon:"◇"},{type:"voice",label:"VOICE",icon:"◖"},
  {type:"music",label:"MUSIC",icon:"♫"},{type:"sfx",label:"SFX",icon:"✦"},{type:"text",label:"TEXT",icon:"T"},{type:"effect",label:"EFFECT",icon:"⚡"},
];
const SCALE=34;
function kind(asset:ProjectAsset):CompositionTrackType { const s=(asset.type+" "+asset.name).toLowerCase(); if(s.includes("video"))return"video";if(s.includes("voice"))return"voice";if(s.includes("music"))return"music";if(s.includes("audio")||s.includes("sfx")||s.includes("sound"))return"sfx";return"visual"; }
function clipColor(type:CompositionTrackType){return type==="video"?"#635bff":type==="voice"?"#8c67ff":type==="music"?"#2f9e72":type==="sfx"?"#d88b35":type==="text"?"#d14f8f":type==="effect"?"#a56dff":"#277ca3"}

export default function AssetComposer({assets,compositions,initial,onSave,onClose}:{assets:ProjectAsset[];compositions:AssetComposition[];initial?:AssetComposition;onSave:(composition:AssetComposition)=>void;onClose:()=>void}) {
 const [name,setName]=useState(initial?.name||"New Action Package"),[clips,setClips]=useState<CompositionClip[]>(initial?.clips||[]),[selected,setSelected]=useState<string|null>(null),[playhead,setPlayhead]=useState(0),[playing,setPlaying]=useState(false); const timer=useRef<number|null>(null),media=useRef<Record<string,HTMLMediaElement|null>>({}),dragging=useRef<{id:string;x:number;start:number}|null>(null);
 const duration=Math.max(1,...clips.map(c=>c.start+c.duration)),selectedClip=clips.find(c=>c.id===selected),preview=clips.filter(c=>c.start<=playhead&&c.start+c.duration>playhead);
 useEffect(()=>{if(!playing){if(timer.current)window.clearInterval(timer.current);return}timer.current=window.setInterval(()=>setPlayhead(t=>t+.05>=duration?0:t+.05),50);return()=>{if(timer.current)window.clearInterval(timer.current)}},[playing,duration]);
 useEffect(()=>{for(const clip of clips){const element=media.current[clip.id];if(!element)continue;const active=playing&&playhead>=clip.start&&playhead<clip.start+clip.duration;if(!active){element.pause();continue}const progress=(playhead-clip.start)*(clip.playbackRate||1),length=Number.isFinite(element.duration)?element.duration:0;const offset=(clip.trimStart||0)+(clip.loop&&length>0?progress%Math.max(.1,length-(clip.trimStart||0)):progress);if(Math.abs(element.currentTime-offset)>.3)try{element.currentTime=offset}catch{};const fadeIn=clip.fadeIn?Math.min(1,(playhead-clip.start)/clip.fadeIn):1,fadeOut=clip.fadeOut?Math.min(1,(clip.start+clip.duration-playhead)/clip.fadeOut):1;element.volume=Math.max(0,Math.min(1,(clip.volume??1)*fadeIn*fadeOut));element.playbackRate=clip.playbackRate||1;if(element.paused)void element.play().catch(()=>{});}},[clips,playhead,playing]);
 const assetOptions=useMemo(()=>assets.filter(a=>a.url),[assets]);
 const source=(clip:CompositionClip)=>assets.find(a=>a.storageKey&&a.storageKey===clip.storageKey)?.url||clip.url;
 function addAsset(asset:ProjectAsset,start=playhead){const track=kind(asset),id=crypto.randomUUID();setClips(v=>[...v,{id,track,assetName:asset.name,storageKey:asset.storageKey,url:asset.storageKey?undefined:asset.url,start,duration:track==="visual"?5:10,trimStart:0,loop:false,volume:1,fadeIn:0,fadeOut:0,playbackRate:1}]);setSelected(id)}
 function addNative(track:"text"|"effect"){const value=window.prompt(track==="text"?"Text to display":"Effect name (confetti, glow, shake, particles…) ",track==="text"?"YOUR TEXT":"Confetti");if(!value?.trim())return;const id=`clip-${Date.now()}`;setClips(v=>[...v,{id,track,assetName:value.trim(),start:0,duration:3,volume:1,fadeIn:.25,fadeOut:.25,playbackRate:1,text:track==="text"?value.trim():undefined,effect:track==="effect"?value.trim():undefined}]);setSelected(id)}
 function patch(p:Partial<CompositionClip>){setClips(v=>v.map(c=>c.id===selected?{...c,...p}:c))}
 function save(){onSave({id:initial?.id||crypto.randomUUID(),name:name.trim()||"Untitled Action Package",duration,clips:clips.map(c=>c.storageKey?{...c,url:undefined}:c),createdAt:initial?.createdAt||new Date().toISOString(),inProject:initial?.inProject||false})}
 return <div className="asset-composer-backdrop"><div className="asset-composer"><header><div><small>PRE-BUILD MEDIA WORKBENCH</small><h2>Asset Composer</h2><p>Stack video, voice, music, SFX, text and effects into one reusable action package.</p></div><button className="media-editor-close" onClick={onClose}>×</button></header>
 <div className="asset-composer-top"><div className="composer-preview">{preview.filter(c=>c.track==="visual").map(c=>source(c)&&<img key={c.id} src={source(c)} alt={c.assetName}/>)}{clips.filter(c=>c.track==="video"&&source(c)).map(c=><video key={c.id} ref={el=>{media.current[c.id]=el}} src={source(c)} preload="auto" playsInline style={{display:preview.includes(c)?"block":"none"}}/>)}{preview.filter(c=>c.track==="text").map(c=><strong key={c.id}>{c.text}</strong>)}{preview.filter(c=>c.track==="effect").map(c=><div key={c.id} className="composer-effect-preview">✦ {c.effect}</div>)}{!preview.some(c=>["visual","video","text","effect"].includes(c.track))&&<span>Move the playhead over a visual clip to preview it.</span>}</div>
 <div className="composer-library"><b>PROJECT ASSETS</b><div>{assetOptions.map((a,i)=><button key={(a.storageKey||a.name)+i} draggable onDragStart={e=>e.dataTransfer.setData("text/plain",String(i))} onClick={()=>addAsset(a)}><span>＋</span>{a.name}<small>{kind(a)}</small></button>)}</div><div className="native-add"><button onClick={()=>addNative("text")}>＋ Text</button><button onClick={()=>addNative("effect")}>＋ Effect</button></div></div></div>
 <div hidden>{clips.filter(c=>["voice","music","sfx"].includes(c.track)&&source(c)).map(c=><audio key={c.id} ref={el=>{media.current[c.id]=el}} src={source(c)} preload="auto"/>)}</div>
 <div className="composer-toolbar"><input value={name} onChange={e=>setName(e.target.value)} aria-label="Composition name"/><button onClick={()=>setPlaying(v=>!v)}>{playing?"❚❚ Pause":"▶ Play"}</button><button onClick={()=>setPlayhead(0)}>↺ Start</button><span>{playhead.toFixed(1)}s / {duration.toFixed(1)}s</span></div>
 <div className="timeline-scroll"><div className="timeline" style={{width:Math.max(720,duration*SCALE+140)}}><div className="timeline-ruler" style={{marginLeft:110}}>{Array.from({length:Math.ceil(duration)+1},(_,i)=><span key={i} style={{left:i*SCALE}}>{i}s</span>)}</div><div className="playhead" style={{left:110+playhead*SCALE}}/>{TRACKS.map(t=><div className="timeline-row" key={t.type}><div className="track-label">{t.icon}<span>{t.label}</span></div><div className="track-lane" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const asset=assetOptions[Number(e.dataTransfer.getData("text/plain"))];if(asset)addAsset(asset,Math.max(0,(e.clientX-e.currentTarget.getBoundingClientRect().left)/SCALE))}} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setPlayhead(Math.max(0,Math.min(duration,(e.clientX-r.left)/SCALE)))}}>{clips.filter(c=>c.track===t.type).map(c=><button key={c.id} className={selected===c.id?"timeline-clip selected":"timeline-clip"} onPointerDown={e=>{dragging.current={id:c.id,x:e.clientX,start:c.start};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const drag=dragging.current;if(drag?.id===c.id)setClips(v=>v.map(item=>item.id===c.id?{...item,start:Math.max(0,Math.round((drag.start+(e.clientX-drag.x)/SCALE)*10)/10)}:item))}} onPointerUp={()=>{dragging.current=null;setSelected(c.id)}} onClick={e=>{e.stopPropagation();setSelected(c.id)}} style={{left:c.start*SCALE,width:Math.max(44,c.duration*SCALE),background:clipColor(c.track)}}><b>{c.assetName}</b><small>{c.duration.toFixed(1)}s</small></button>)}</div></div>)}</div></div>
 {selectedClip&&<div className="clip-inspector"><div><b>{selectedClip.assetName}</b><small>{selectedClip.track.toUpperCase()} CLIP</small></div><label>Start<input type="number" min="0" step=".1" value={selectedClip.start} onChange={e=>patch({start:Math.max(0,+e.target.value)})}/></label><label>Duration<input type="number" min=".1" step=".1" value={selectedClip.duration} onChange={e=>patch({duration:Math.max(.1,+e.target.value)})}/></label>{["voice","music","sfx","video"].includes(selectedClip.track)&&<><label>Trim start<input type="number" min="0" step=".1" value={selectedClip.trimStart||0} onChange={e=>patch({trimStart:Math.max(0,+e.target.value)})}/></label><label>Volume<input type="range" min="0" max="1" step=".05" value={selectedClip.volume} onChange={e=>patch({volume:+e.target.value})}/></label><label>Fade in<input type="number" min="0" step=".1" value={selectedClip.fadeIn} onChange={e=>patch({fadeIn:Math.max(0,+e.target.value)})}/></label><label>Fade out<input type="number" min="0" step=".1" value={selectedClip.fadeOut} onChange={e=>patch({fadeOut:Math.max(0,+e.target.value)})}/></label><label>Speed<input type="number" min=".25" max="4" step=".25" value={selectedClip.playbackRate} onChange={e=>patch({playbackRate:Math.max(.25,Math.min(4,+e.target.value))})}/></label><label>Loop<input type="checkbox" checked={!!selectedClip.loop} onChange={e=>patch({loop:e.target.checked})}/></label></>}{["text","effect"].includes(selectedClip.track)&&<label>Content<input value={selectedClip.text||selectedClip.effect||""} onChange={e=>patch(selectedClip.track==="text"?{text:e.target.value,assetName:e.target.value}:{effect:e.target.value,assetName:e.target.value})}/></label>}<button className="danger-btn" onClick={()=>{setClips(v=>v.filter(c=>c.id!==selected));setSelected(null)}}>Remove clip</button></div>}
 <footer><div><b>{clips.length} clips</b><span> · {compositions.length} saved packages in this project</span></div><div><button className="outline-btn" onClick={onClose}>Cancel</button><button className="build-btn" disabled={!clips.length} onClick={save}>Save Composition</button></div></footer></div></div>
}
