"use client";
import { useState, useEffect, useRef, type ReactNode } from "react";
import type { Project, ProjectEvent, ProjectAsset, GameTool } from "../lib/project";
import type { YouTubeState } from "../lib/youtube";
import { safeYoutubePlacement } from "../lib/youtube";
import { defaultOverlayResult } from "./CompositionPlayer";
import WheelHostPanel from "./WheelHostPanel";
import QuestionCardEditor from "./QuestionCardEditor";
import GameToolEditor from "./GameToolEditor";
import {assignControlAction} from "../lib/control-connections";
import {addCreationControl} from "../lib/build-controls";
import {additionTypes,creationsForType,creationControls,type AdditionType,type BuildCreation} from "../lib/build-guide";
import {mediaKind} from "../lib/board-design";
import {buildReadiness} from "../lib/build-readiness";
import {cardControl} from "../lib/question-cards";
import { ControlAppearancePreview } from "./RuntimeActionLayers";
import YouTubePlacementEditor from "./YouTubePlacementEditor";
import YouTubeHostPanel from "./YouTubeHostPanel";

type Props={project:Project;onChange:(project:Project)=>void;overlay:ReactNode;onTrigger:(control:ProjectEvent)=>void;onWorkshop:()=>void;youtubeOpen:boolean;onCloseYoutube:()=>void;onYoutubeCommand:(command:Record<string,unknown>)=>Promise<YouTubeState>;youtubeState:YouTubeState|null;youtubeFeedback:{playbackId:string;status:string;errorCode?:number}|null;dashboardExtras?:(toolId?:string)=>ReactNode;feedback?:string;onPublishStep:()=>void};
export default function BuildSpace({project,onChange,overlay,onTrigger,onWorkshop,youtubeOpen,onCloseYoutube,onYoutubeCommand,youtubeState,youtubeFeedback,dashboardExtras,feedback,onPublishStep}:Props){
 const [testing,setTesting]=useState(false),[selection,setSelection]=useState<{kind:"asset"|"tool"|"control";id:string}|null>(null);
 const [step,setStep]=useState(0);
 const [additionType,setAdditionType]=useState<AdditionType>("image");
 const [activeCreation,setActiveCreation]=useState<BuildCreation|null>(null);
 const guide=additionTypes.find(item=>item.id===additionType)!;
 const choices=creationsForType(project,additionType);
 const connected=activeCreation?creationControls(project,activeCreation):[];
 const hasBackground=project.assets.some(a=>a.inProject&&a.role==="background")||project.gameTools.some(t=>t.enabled&&t.inOverlayBuild&&(t.type==="blank-board"||t.type==="trivia-board"));
 function nextType(){const index=additionTypes.findIndex(t=>t.id===additionType);setActiveCreation(null);setSelection(null);setTesting(false);if(index===additionTypes.length-1){goStep(3);}else{setAdditionType(additionTypes[index+1].id);setStep(1);}}
 const settings=useRef<HTMLElement>(null);
 useEffect(()=>{if(selection&&!testing)settings.current?.scrollIntoView({behavior:"smooth",block:"nearest"});},[selection,testing]);
 const issues=buildReadiness(project);
 function goStep(next:number){setStep(next);setTesting(next===3);setSelection(null);}
 const key=(asset:ProjectAsset)=>asset.storageKey||asset.name;
 const asset=project.assets.find(a=>selection?.kind==="asset"?key(a)===selection.id:selection?.kind==="control"?project.controls.find(c=>c.id===selection.id)?.action===`asset.show.${key(a)}`:false);
 const tool=project.gameTools.find(t=>selection?.kind==="tool"?t.id===selection.id:selection?.kind==="control"?project.controls.find(c=>c.id===selection.id)?.toolIds?.includes(t.id):false);
 const control=selection?.kind==="control"?project.controls.find(c=>c.id===selection.id):undefined;
 const hasVisualResult=!!control&&!control.action.startsWith("result.hide.")&&(!asset||mediaKind(asset)!=="audio");
 const youtube=project.gameTools.find(t=>t.type==="youtube"&&t.enabled);
 function updateControl(id:string,patch:Partial<ProjectEvent>){onChange({...project,controls:project.controls.map(c=>c.id===id?{...c,...patch}:c)});}
 function updateAsset(id:string,patch:Partial<ProjectAsset>){onChange({...project,assets:project.assets.map(a=>key(a)===id?{...a,...patch}:a)});}
 function chooseCreation(kind:'asset'|'tool'|'composition',id:string){setActiveCreation(choices.find(c=>c.kind===kind&&c.id===id)||null);const result=addCreationControl(project,kind,id);onChange(result.project);setStep(2);setTesting(false);setSelection({kind:'control',id:result.controlId});}
 function applyBackground(id:string,board=false){onChange({...project,assets:project.assets.map(a=>({...a,inProject:board?(a.role==='background'?false:a.inProject):(key(a)===id?true:a.role==='background'?false:a.inProject),role:!board&&key(a)===id?'background':a.role})),gameTools:project.gameTools.map(t=>(t.type==='blank-board'||t.type==='trivia-board')?{...t,inOverlayBuild:board&&t.id===id,config:{...t.config,triggerOnly:false}}:t)});}
 function drop(e:React.DragEvent){e.preventDefault();try{const item=JSON.parse(e.dataTransfer.getData('application/ttc-creation'));if(['asset','tool','composition'].includes(item.kind))chooseCreation(item.kind,item.id);}catch{}}

 return <section className="build-space" aria-label="Build Space assembly">
  <header className="build-space-toolbar"><div><h2>Build Space</h2><p>{testing?"Rehearse the dashboard and its paired overlay. These actions stay in your draft.":"Start with a background or board. Then add creations and configure their dashboard controls and overlay appearance."}</p></div><button type="button" className="build-btn" aria-pressed={testing} onClick={()=>{setActiveCreation(null);goStep(testing?2:3);}}>{testing?"Return to assembly":"Test dashboard & overlay"}</button></header>
  <nav className="build-steps" aria-label="Build Space steps">{['Background / board','Choose additions','Set up this addition','Rehearse','Ready to publish'].map((label,index)=><button type="button" key={label} aria-current={step===index?'step':undefined} onClick={()=>{if(index===3)setActiveCreation(null);goStep(index);}}><span>{index+1}</span>{label}</button>)}</nav>
  <section className="build-guidance" aria-label="Current build step"><h3>{['Set your initial background','Choose the next addition','Choose how this addition looks and works','Play a complete round','Review before publishing'][step]}</h3><p>{['Choose a still image, animated background, or a board designed in Workshop. This is the starting scene.','Choose something you made in Workshop. We’ll add the matching dashboard buttons. You’ll then choose how it looks and try it. It stays hidden until you press its button.','The selected result is shown here only as an editing preview. Adjust its appearance and placement, name its controls, then test them.','Use the dashboard to show, reveal, play, and hide your additions. The background starts with the scene; game actions start only when you trigger them.','Fix missing connections and check a complete round before publishing.'][step]}</p>{step<4&&step!==1&&step!==2&&<button type="button" disabled={step===0&&!hasBackground} onClick={()=>goStep(step+1)}>Next: {['Choose additions','Set up this addition','Rehearse','Ready to publish'][step]}</button>}</section>
  {step===0&&<section className="creation-tray" aria-label="Initial background"><h3>Choose the initial background or board</h3>{project.assets.filter(a=>['image','video'].includes(mediaKind(a))).map(a=><article key={key(a)}><strong>{a.name}</strong><small>{mediaKind(a)==='video'?'Animated background':'Image background'}</small><button type="button" onClick={()=>applyBackground(key(a))}>{a.inProject&&a.role==='background'?'Current background':'Use as initial background'}</button></article>)}{project.gameTools.filter(t=>t.enabled&&(t.type==='blank-board'||t.type==='trivia-board')).map(t=><article key={t.id}><strong>{t.name}</strong><button type="button" onClick={()=>applyBackground(t.id,true)}>{t.inOverlayBuild?'Current board':'Use as initial board'}</button></article>)}<button type="button" onClick={onWorkshop}>Create or design in Workshop</button></section>}
  {step===4&&<section className="build-readiness" aria-label="Game readiness"><h3>{issues.length?`${issues.length} connection issues to fix`:'No connection issues detected'}</h3>{issues.length?issues.map(issue=><div key={issue.id}><p>{issue.message}</p><button type="button" onClick={()=>{goStep(2);setSelection({kind:issue.kind,id:issue.targetId});}}>Fix connection</button></div>):<p>Check your game's rules, media playback, and complete round in rehearsal before publishing.</p>}<button type="button" onClick={()=>goStep(3)}>Rehearse game</button><button type="button" disabled={issues.length>0} onClick={onPublishStep}>Continue to Publish</button></section>}
  {!testing&&(step===1||step===2)&&<section className="addition-guide" aria-label="Additions guide">
   <h3>Add one type at a time</h3><p>Choose only what your game needs. You can skip a type or return to it later.</p>
   <nav className="addition-types" aria-label="Addition types">{additionTypes.map(item=><button type="button" key={item.id} aria-pressed={additionType===item.id} onClick={()=>{setAdditionType(item.id);setStep(1);setSelection(null);setActiveCreation(null);}}>{item.label}<small>{creationsForType(project,item.id).length} available</small></button>)}</nav>
   <h4>{guide.label}</h4><p>{guide.help}</p>
   <ol className="addition-checklist"><li>Choose your Workshop creation.</li><li>Choose how it looks. Its dashboard buttons are added for you.</li><li>Test the buttons beside the overlay, then add another item or continue.</li></ol>
   {(step===1||!selection)&&<div className="creation-tray" aria-label="Workshop creations">{choices.map(c=><article key={c.id}><strong>{c.name}</strong><small>{creationControls(project,c).length?'Controls connected':'Ready to set up'}</small><button type="button" onClick={()=>chooseCreation(c.kind,c.id)}>{creationControls(project,c).length?'Set up this item':'Use this in my game'}</button></article>)}{!choices.length&&<p>No {guide.label.toLowerCase()} available yet. Create or upload one in Workshop, or skip this type.</p>}</div>}
   {step===2&&activeCreation&&<section aria-label="Connected dashboard buttons"><h4>{activeCreation.name}</h4><p>These buttons are ready to use. Choose one below if you want to rename it or adjust what appears.</p><div className="placed-items">{connected.map(c=><button type="button" key={c.id} aria-pressed={control?.id===c.id} onClick={()=>setSelection({kind:'control',id:c.id})}>{c.label}</button>)}</div></section>}
   <div className="addition-actions"><button type="button" onClick={onWorkshop}>Create in Workshop</button>{step===2&&<><button type="button" onClick={()=>goStep(3)}>Test this addition</button><button type="button" onClick={()=>{setStep(1);setSelection(null);}}>Add another {guide.label.toLowerCase()}</button></>}<button type="button" onClick={nextType}>{step===1?'Skip / next type':'Done / next type'}</button><button type="button" onClick={()=>{setActiveCreation(null);goStep(3);}}>Review the whole game</button></div>
   <p>Boards are backgrounds. Question pools are selected inside the card setup.</p>
  </section>}
  {testing&&activeCreation&&<section className="build-guidance" aria-label="Test this addition"><h3>Test {activeCreation.name}</h3><p>Use its controls below. Check the result appears only when requested, looks right, and can be cleared or stopped.</p><div className="placed-items">{connected.map(c=><button type="button" key={c.id} onClick={()=>onTrigger(c)}>{c.label}</button>)}<button type="button" onClick={()=>{setTesting(false);setStep(2);setSelection(connected[0]?{kind:'control',id:connected[0].id}:null);}}>Adjust this addition</button><button type="button" onClick={nextType}>Done / next type</button></div></section>}
  <div role="status" aria-live="polite">{feedback}</div>
  <div className="paired-canvases" hidden={step===1||step===4}>
   <section className="assembly-canvas"><h3>Draft overlay{testing?" preview":""}</h3><div className="stage" >{overlay}{!testing&&control&&hasVisualResult&&!cardControl(control.action)&&<ControlAppearancePreview control={{...control,overlayResult:control.overlayResult||defaultOverlayResult}} project={project}/>}
    {!testing&&!project.assets.some(a=>a.inProject)&&!project.gameTools.some(t=>t.inOverlayBuild)&&<p className="canvas-empty">Choose a background first. Add other creations through their dashboard controls.</p>}
    {!testing&&asset?.inProject&&asset.role!=="background"&&!asset.type.includes("audio")&&<YouTubePlacementEditor label={asset.name} placement={asset.edits?.placement||{x:5,y:20,width:40,height:40}} onChange={placement=>updateAsset(key(asset),{edits:{...asset.edits,placement}})}/>}
    {!testing&&tool&&(!control||tool.type==="youtube")&&tool.inOverlayBuild&&tool.type!=="question-card"&&tool.type!=="blank-card"&&tool.type!=="random-picker"&&<YouTubePlacementEditor label={tool.type==="youtube"?"YouTube":tool.name} placement={tool.config.placement as {x:number;y:number;width:number;height:number}||{x:15,y:15,width:70,height:70}} onChange={placement=>onChange({...project,gameTools:project.gameTools.map(t=>t.id===tool.id?{...t,config:{...t.config,placement}}:t)})}/>}
    {!testing&&control&&hasVisualResult&&!cardControl(control.action)&&!control.action.startsWith("background.show.")&&!control.toolIds?.some(id=>project.gameTools.find(t=>t.id===id)?.type==="youtube")&&<YouTubePlacementEditor label={control.label} placement={control.overlayResult||defaultOverlayResult} onChange={placement=>updateControl(control.id,{overlayResult:{...(control.overlayResult||defaultOverlayResult),...placement}})}/>}
   </div>{!testing&&<div className="placed-items" aria-label="Placed overlay items">{project.assets.filter(a=>a.inProject).map(a=><button key={key(a)} type="button" onClick={()=>(setStep(2),setSelection({kind:"asset",id:key(a)}))}>{a.name}</button>)}{project.gameTools.filter(t=>t.inOverlayBuild).map(t=><button key={t.id} type="button" onClick={()=>(setStep(2),setSelection({kind:"tool",id:t.id}))}>{t.type==="youtube"?"Video destination":t.name}</button>)}</div>}</section>
   <section className="assembly-canvas" hidden={step===0}><h3>Host dashboard{testing?" preview":""}</h3><div className="dashboard-canvas" onDragOver={e=>e.preventDefault()} onDrop={drop}>
    {!project.controls.length&&!dashboardExtras&&<p className="canvas-empty">Place your host controls here.</p>}
    <div className="dashboard-preview-buttons">{(activeCreation?connected:project.controls).map(c=><button type="button" key={c.id} aria-pressed={!testing&&control?.id===c.id} onClick={()=>testing?onTrigger(c):(setStep(2),setSelection({kind:"control",id:c.id}))}>{c.label}<small>{c.detail||"Choose an action"}</small></button>)}</div>
    {testing&&dashboardExtras?.(activeCreation?.kind==="tool"?activeCreation.id:activeCreation?"media-only":undefined)}
    {testing&&project.gameTools.filter(t=>t.enabled&&t.inToolbox&&t.type==="wheel"&&(!activeCreation||activeCreation.id===t.id)).map(t=><WheelHostPanel key={t.id} tool={t} onSave={segments=>onChange({...project,gameTools:project.gameTools.map(x=>x.id===t.id?{...x,config:{...x.config,segments}}:x)})}/>)}
    {testing&&youtubeOpen&&youtube&&<div className="youtube-draft-testing"><button type="button" className="outline-btn" onClick={onCloseYoutube}>Close private tool</button>{!youtube.inOverlayBuild&&<p>Private search and listening are available. Configure its overlay destination to test showing a clip.</p>}<YouTubeHostPanel canShow={Boolean(youtube.inOverlayBuild)} onCommand={onYoutubeCommand} previewState={youtubeState} previewFeedback={youtubeFeedback} placement={safeYoutubePlacement(youtube.config.placement)}/></div>}
   </div>{!testing&&<p>Add a working control from a Workshop creation above.</p>}</section>
  </div>
  {!testing&&selection&&<section ref={settings} className="assembly-settings" aria-label="Selected item settings"><h3>Set up: {asset?.name||tool?.name||control?.label}</h3>
   {asset&&<><button type="button" onClick={onWorkshop}>Edit or upload in Workshop</button><p>{mediaKind(asset)==="audio"?"Audio playback":asset.role==="background"&&asset.inProject?"Initial background":"Shown by its dashboard control"}</p>{(asset.type.includes("video")||asset.type.includes("audio"))&&<><label>Loop<input type="checkbox" checked={asset.edits?.loop??false} onChange={e=>updateAsset(key(asset),{edits:{...asset.edits,loop:e.target.checked}})}/></label><label>Sound<input type="checkbox" checked={asset.edits?.sound??mediaKind(asset)==="audio"} onChange={e=>updateAsset(key(asset),{edits:{...asset.edits,sound:e.target.checked}})}/></label><label>Volume<input type="range" min="0" max="100" value={asset.edits?.volume??80} onChange={e=>updateAsset(key(asset),{edits:{...asset.edits,volume:+e.target.value}})}/></label></>}{asset.inProject&&<button type="button" onClick={()=>{updateAsset(key(asset),{inProject:false});setSelection(null);}}>Remove from overlay</button>}</>}
   {tool&&(tool.type==="question-card"||tool.type==="blank-card")&&<QuestionCardEditor key={tool.id} project={project} tool={tool} onSave={next=>onChange({...project,gameTools:project.gameTools.map(t=>t.id===next.id?next:t)})}/>}
   {tool?.type==="question-card"&&<button type="button" onClick={()=>chooseCreation('tool',tool.id)}>Connect cards and Show / Reveal controls</button>}

   {tool?.type==="random-picker"&&<p>Each card uses its own Workshop design and placement. Connect a saved list below, save, then test Pick next card and Hide. Start new game is available in rehearsal and on the host dashboard.</p>}{tool&&!["question-card","blank-card","youtube","blank-board","trivia-board"].includes(tool.type)&&<GameToolEditor key={tool.id} project={project} tool={tool} assets={project.assets} onSave={next=>onChange({...project,gameTools:project.gameTools.map(t=>t.id===next.id?next:t)})}/>}
   {tool&&<><p>{tool.type==="youtube"?"This is the destination for videos chosen during the game. It stays hidden until the host sends a clip.":"This result waits for its dashboard control during play."}</p><button type="button" onClick={()=>{onChange({...project,gameTools:project.gameTools.map(t=>t.id===tool.id?{...t,inOverlayBuild:false}:t)});setSelection(null);}}>Remove from overlay</button></>}
   {tool?.type==='blank-card'&&<label>Text shown by this card button<textarea value={String(tool.config.text||'')} onChange={e=>onChange({...project,gameTools:project.gameTools.map(t=>t.id===tool.id?{...t,config:{...t.config,text:e.target.value}}:t)})}/></label>}
   {control&&<><label>Button name on your dashboard<input value={control.label} onChange={e=>updateControl(control.id,{label:e.target.value})}/></label><p><strong>What this button does:</strong> {control.detail}</p><details className="build-advanced"><summary>Change the connected action (optional)</summary><p>A working action is already connected. Change it only if you want this button to do something different.</p><label>When I press this button<select value={control.action||""} onChange={e=>{const action=e.target.value,t=project.gameTools.find(t=>action===`tool.${t.id}`||t.id===cardControl(action)?.toolId),composition=project.compositions?.find(c=>action===`composition.play.${c.id}`);onChange({...project,gameTools:project.gameTools.map(x=>x.id===t?.id?{...x,inToolbox:true}:x),compositions:project.compositions?.map(x=>x.id===composition?.id?{...x,inProject:true}:x),controls:project.controls.map(c=>c.id===control.id?assignControlAction(project,c,action):c)});}}><option value="">Choose an action</option>{(control.action.startsWith("asset.")||control.action.startsWith("result.")||control.action.startsWith("cards.blank."))&&<option value={control.action}>{control.detail}</option>}{project.gameTools.filter(t=>t.enabled&&t.type==="random-picker").flatMap(t=>[["draw","Pick next card"],["clear","Hide picked card"]].map(([action,label])=><option key={t.id+action} value={`cards.${action}.${t.id}`}>{t.name}: {label}</option>))}{project.gameTools.filter(t=>t.enabled&&t.type==="question-card").flatMap(t=>[["show","Show Question"],["reveal","Reveal Answer"],["clear","Clear card"]].map(([action,label])=><option key={t.id+action} value={`cards.${action}.${t.id}`}>{t.name}: {label}</option>))}{project.gameTools.filter(t=>t.enabled&&t.type!=="question-card"&&t.type!=="blank-card"&&t.type!=="card-list"&&t.type!=="random-picker").map(t=><option key={t.id} value={`tool.${t.id}`}>{t.type==="youtube"?"Open private search: ":"Trigger: "}{t.name}</option>)}{project.assets.filter(a=>!a.type.includes("audio")).map(a=><option key={key(a)} value={`background.show.${key(a)}`}>Show background: {a.name}</option>)}{project.compositions?.map(c=><option key={c.id} value={`composition.play.${c.id}`}>Play scene: {c.name}</option>)}</select></label></details><p>During a game, the host presses this saved button. Use rehearsal to check its result and the matching clear or stop button.</p><button type="button" onClick={()=>{onChange({...project,controls:project.controls.filter(c=>c.id!==control.id)});setSelection(null);}}>Remove from dashboard</button></>}
  </section>}
 </section>;
}

