"use client";
import { useState, type ReactNode } from "react";
import type { Project, ProjectEvent, ProjectAsset, GameTool } from "../lib/project";
import type { YouTubeState } from "../lib/youtube";
import { safeYoutubePlacement } from "../lib/youtube";
import { defaultOverlayResult } from "./CompositionPlayer";
import QuestionCardEditor from "./QuestionCardEditor";
import GameToolEditor from "./GameToolEditor";
import {assignControlAction,connectQuestionCard} from "../lib/control-connections";
import {cardControl} from "../lib/question-cards";
import { ControlAppearancePreview } from "./RuntimeActionLayers";
import YouTubePlacementEditor from "./YouTubePlacementEditor";
import YouTubeHostPanel from "./YouTubeHostPanel";

type Props={project:Project;onChange:(project:Project)=>void;overlay:ReactNode;onTrigger:(control:ProjectEvent)=>void;onWorkshop:()=>void;youtubeOpen:boolean;onCloseYoutube:()=>void;onYoutubeCommand:(command:Record<string,unknown>)=>Promise<YouTubeState>;youtubeState:YouTubeState|null;youtubeFeedback:{playbackId:string;status:string;errorCode?:number}|null;dashboardExtras?:ReactNode;feedback?:string};
export default function BuildSpace({project,onChange,overlay,onTrigger,onWorkshop,youtubeOpen,onCloseYoutube,onYoutubeCommand,youtubeState,youtubeFeedback,dashboardExtras,feedback}:Props){
 const [testing,setTesting]=useState(false),[selection,setSelection]=useState<{kind:"asset"|"tool"|"control";id:string}|null>(null);
 const key=(asset:ProjectAsset)=>asset.storageKey||asset.name;
 const asset=selection?.kind==="asset"?project.assets.find(a=>key(a)===selection.id):undefined;
 const tool=selection?.kind==="tool"?project.gameTools.find(t=>t.id===selection.id):undefined;
 const control=selection?.kind==="control"?project.controls.find(c=>c.id===selection.id):undefined;
 const youtube=project.gameTools.find(t=>t.type==="youtube"&&t.enabled);
 function updateControl(id:string,patch:Partial<ProjectEvent>){onChange({...project,controls:project.controls.map(c=>c.id===id?{...c,...patch}:c)});}
 function updateAsset(id:string,patch:Partial<ProjectAsset>){onChange({...project,assets:project.assets.map(a=>key(a)===id?{...a,...patch}:a)});}
 function placeAsset(id:string,background:boolean){onChange({...project,assets:project.assets.map(a=>key(a)===id?{...a,inProject:true,role:background?"background":a.type.includes("audio")?"audio":"layer"}:background&&a.role==="background"?{...a,inProject:false}:a)});setSelection({kind:"asset",id});}
 function placeTool(id:string,dashboard:boolean){const t=project.gameTools.find(t=>t.id===id);if(!t)return;if(dashboard&&t.type==="blank-card"){onChange({...project,gameTools:project.gameTools.map(x=>x.id===id?{...x,inToolbox:true,inOverlayBuild:true}:x)});setSelection({kind:"tool",id});return;}if(dashboard&&t.type==="question-card"){const next=connectQuestionCard(project,id);onChange(next);setSelection({kind:"control",id:next.controls.find(c=>c.action===`cards.show.${id}`)!.id});return;}if(dashboard){const existing=project.controls.find(c=>c.toolIds?.includes(id));if(existing){setSelection({kind:"control",id:existing.id});return;}const next:ProjectEvent={id:crypto.randomUUID(),label:t.name,action:`tool.${id}`,detail:`Open ${t.name}`,buttonMode:"single",toolIds:[id],chain:[]};onChange({...project,gameTools:project.gameTools.map(x=>x.id===id?{...x,inToolbox:true}:x),controls:[...project.controls,next]});setSelection({kind:"control",id:next.id});}else{onChange({...project,gameTools:project.gameTools.map(x=>x.id===id?{...x,inOverlayBuild:true}:x)});setSelection({kind:"tool",id});}}
 function newControl(){const c:ProjectEvent={id:crypto.randomUUID(),label:"New control",action:"",detail:"Unassigned dashboard button",toolIds:[],chain:[]};onChange({...project,controls:[...project.controls,c]});setSelection({kind:"control",id:c.id});}
 function drop(e:React.DragEvent,dashboard:boolean){e.preventDefault();const raw=e.dataTransfer.getData("application/ttc-creation");try{const item=JSON.parse(raw);if(item.kind==="tool")placeTool(item.id,dashboard);if(item.kind==="asset"&&!dashboard)placeAsset(item.id,false);}catch{}}
 const drag=(e:React.DragEvent,kind:string,id:string)=>e.dataTransfer.setData("application/ttc-creation",JSON.stringify({kind,id}));
 return <section className="build-space" aria-label="Build Space assembly">
  <header className="build-space-toolbar"><div><h2>Build Space</h2><p>{testing?"Rehearse the dashboard and its paired overlay. These actions stay in your draft.":"Place your Workshop creations, choose what your controls do, then rehearse."}</p></div><button type="button" className="build-btn" aria-pressed={testing} onClick={()=>{setTesting(!testing);setSelection(null);}}>{testing?"Return to assembly":"Test dashboard & overlay"}</button></header>
  {!testing&&<aside className="creation-tray" aria-label="Workshop creations"><h3>Workshop creations</h3>{!project.assets.length&&!project.gameTools.length&&!project.compositions?.length&&<p>No creations yet. Return to Workshop to create your pieces.</p>}
   {project.assets.map((a,i)=><article key={key(a)+i} draggable onDragStart={e=>drag(e,"asset",key(a))}><strong>{a.name}</strong><small>{a.type}</small><button type="button" onClick={()=>placeAsset(key(a),false)}>Place on overlay</button>{!a.type.includes("audio")&&<button type="button" onClick={()=>placeAsset(key(a),true)}>Use as background</button>}</article>)}
   {project.gameTools.filter(t=>t.enabled).map(t=><article key={t.id} draggable onDragStart={e=>drag(e,"tool",t.id)}><strong>{t.name}</strong><small>{t.type}</small><button type="button" onClick={()=>placeTool(t.id,true)}>Place on dashboard</button><button type="button" onClick={()=>placeTool(t.id,false)}>{t.type==="youtube"?"Place video destination on overlay":"Place on overlay"}</button></article>)}
   {(project.compositions||[]).map(c=><article key={c.id}><strong>{c.name}</strong><small>Scene / composition</small><button type="button" onClick={()=>{const existing=project.controls.find(x=>x.compositionId===c.id);if(existing){setSelection({kind:"control",id:existing.id});return;}const control:ProjectEvent={id:crypto.randomUUID(),label:c.name,action:`composition.play.${c.id}`,detail:`Play ${c.name}`,compositionId:c.id,overlayResult:{...defaultOverlayResult}};onChange({...project,compositions:project.compositions?.map(x=>x.id===c.id?{...x,inProject:true}:x),controls:[...project.controls,control]});setSelection({kind:"control",id:control.id});}}>Place scene control on dashboard</button></article>)}
   <button type="button" className="outline-btn" onClick={onWorkshop}>Return to Workshop</button>
  </aside>}
  <div role="status" aria-live="polite">{testing&&feedback}</div>
  <div className="paired-canvases">
   <section className="assembly-canvas"><h3>Draft overlay{testing?" preview":""}</h3><div className="stage" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,false)}>{overlay}{!testing&&control&&!cardControl(control.action)&&<ControlAppearancePreview control={{...control,overlayResult:control.overlayResult||defaultOverlayResult}} project={project}/>}
    {!testing&&!project.assets.some(a=>a.inProject)&&!project.gameTools.some(t=>t.inOverlayBuild)&&<p className="canvas-empty">Place the creations you want your audience to see here.</p>}
    {!testing&&asset?.inProject&&asset.role!=="background"&&!asset.type.includes("audio")&&<YouTubePlacementEditor label={asset.name} placement={asset.edits?.placement||{x:5,y:20,width:40,height:40}} onChange={placement=>updateAsset(key(asset),{edits:{...asset.edits,placement}})}/>}
    {!testing&&tool&&tool.inOverlayBuild&&tool.type!=="question-card"&&tool.type!=="blank-card"&&<YouTubePlacementEditor label={tool.type==="youtube"?"YouTube":tool.name} placement={tool.config.placement as {x:number;y:number;width:number;height:number}||{x:15,y:15,width:70,height:70}} onChange={placement=>onChange({...project,gameTools:project.gameTools.map(t=>t.id===tool.id?{...t,config:{...t.config,placement}}:t)})}/>}
    {!testing&&control&&!cardControl(control.action)&&!control.action.startsWith("background.show.")&&!control.toolIds?.some(id=>project.gameTools.find(t=>t.id===id)?.type==="youtube")&&<YouTubePlacementEditor label={control.label} placement={control.overlayResult||defaultOverlayResult} onChange={placement=>updateControl(control.id,{overlayResult:{...(control.overlayResult||defaultOverlayResult),...placement}})}/>}
   </div>{!testing&&<div className="placed-items" aria-label="Placed overlay items">{project.assets.filter(a=>a.inProject).map(a=><button key={key(a)} type="button" onClick={()=>setSelection({kind:"asset",id:key(a)})}>{a.name}</button>)}{project.gameTools.filter(t=>t.inOverlayBuild).map(t=><button key={t.id} type="button" onClick={()=>setSelection({kind:"tool",id:t.id})}>{t.type==="youtube"?"Video destination":t.name}</button>)}</div>}</section>
   <section className="assembly-canvas"><h3>Draft dashboard{testing?" preview":""}</h3><div className="dashboard-canvas" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,true)}>
    {!project.controls.length&&!dashboardExtras&&<p className="canvas-empty">Place your host controls here.</p>}
    <div className="dashboard-preview-buttons">{project.controls.map(c=><button type="button" key={c.id} aria-pressed={!testing&&control?.id===c.id} onClick={()=>testing?onTrigger(c):setSelection({kind:"control",id:c.id})}>{c.label}</button>)}</div>
    {testing&&dashboardExtras}
    {testing&&youtubeOpen&&youtube&&<div className="youtube-draft-testing"><button type="button" className="outline-btn" onClick={onCloseYoutube}>Close private tool</button>{!youtube.inOverlayBuild&&<p>Private search and listening are available. Place a video destination in assembly to test showing a clip on the overlay.</p>}<YouTubeHostPanel canShow={Boolean(youtube.inOverlayBuild)} onCommand={onYoutubeCommand} previewState={youtubeState} previewFeedback={youtubeFeedback} placement={safeYoutubePlacement(youtube.config.placement)}/></div>}
   </div>{!testing&&<button type="button" className="outline-btn" onClick={newControl}>Add a blank control</button>}</section>
  </div>
  {!testing&&selection&&<section className="assembly-settings" aria-label="Selected item settings"><h3>Selected: {asset?.name||tool?.name||control?.label}</h3>
   {asset&&<><p>{asset.role==="background"?"Background layer":"Overlay layer"}</p>{(asset.type.includes("video")||asset.type.includes("audio"))&&<><label>Loop<input type="checkbox" checked={asset.edits?.loop??true} onChange={e=>updateAsset(key(asset),{edits:{...asset.edits,loop:e.target.checked}})}/></label><label>Sound<input type="checkbox" checked={asset.edits?.sound??false} onChange={e=>updateAsset(key(asset),{edits:{...asset.edits,sound:e.target.checked}})}/></label><label>Volume<input type="range" min="0" max="100" value={asset.edits?.volume??80} onChange={e=>updateAsset(key(asset),{edits:{...asset.edits,volume:+e.target.value}})}/></label></>}<button type="button" onClick={()=>{updateAsset(key(asset),{inProject:false});setSelection(null);}}>Remove from overlay</button></>}
   {tool&&(tool.type==="question-card"||tool.type==="blank-card")&&<QuestionCardEditor key={`${tool.id}:${tool.config.turnTimerId||''}:${tool.config.stealTimerId||''}`} project={project} tool={tool} onSave={next=>onChange({...project,gameTools:project.gameTools.map(t=>t.id===next.id?next:t)})}/>}
   {tool?.type==="question-card"&&<section aria-label="Optional card timer connections"><h4>Optional timer connections</h4><p>Cards work without timers. Connect a timer here only if your game needs it.</p>{(['turnTimerId','stealTimerId'] as const).map((field,i)=><label key={field}>{i?'Steal timer (optional)':'Player Turn timer (optional)'}<select value={String(tool.config[field]||'')} onChange={e=>{const value=e.target.value;onChange({...project,gameTools:project.gameTools.map(t=>t.id===tool.id?{...t,config:{...t.config,[field]:value}}:t)});}}><option value="">No timer</option>{project.gameTools.filter(t=>t.type==='countdown'&&t.enabled&&t.id!==tool.config[i?'turnTimerId':'stealTimerId']).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>)}</section>}
   {tool&&tool.type==="countdown"&&<GameToolEditor key={tool.id} project={project} tool={tool} assets={project.assets} onSave={next=>onChange({...project,gameTools:project.gameTools.map(t=>t.id===next.id?next:t)})}/>}
   {tool&&<><p>{tool.type==="youtube"?"This is the destination for videos chosen during the game. It stays hidden until the host sends a clip.":"This creation is placed on the draft overlay."}</p><button type="button" onClick={()=>{onChange({...project,gameTools:project.gameTools.map(t=>t.id===tool.id?{...t,inOverlayBuild:false}:t)});setSelection(null);}}>Remove from overlay</button></>}
   {control&&<><label>Control label<input value={control.label} onChange={e=>updateControl(control.id,{label:e.target.value})}/></label><label>Action<select value={control.action||""} onChange={e=>{const action=e.target.value,t=project.gameTools.find(t=>action===`tool.${t.id}`||t.id===cardControl(action)?.toolId),composition=project.compositions?.find(c=>action===`composition.play.${c.id}`);onChange({...project,gameTools:project.gameTools.map(x=>x.id===t?.id?{...x,inToolbox:true}:x),compositions:project.compositions?.map(x=>x.id===composition?.id?{...x,inProject:true}:x),controls:project.controls.map(c=>c.id===control.id?assignControlAction(project,c,action):c)});}}><option value="">Choose an action</option>{project.gameTools.filter(t=>t.enabled&&t.type==="question-card").flatMap(t=>[["show","Show Question"],["turn","Start Player Turn"],["steal","Start Steal"],["reveal","Finish and reveal answer"],["clear","Clear card"]].filter(([action])=>action!=="turn"&&action!=="steal"||project.gameTools.some(timer=>timer.enabled&&timer.type==="countdown"&&timer.id===t.config[action==="turn"?"turnTimerId":"stealTimerId"])).map(([action,label])=><option key={t.id+action} value={`cards.${action}.${t.id}`}>{t.name}: {label}</option>))}{project.gameTools.filter(t=>t.enabled&&t.type!=="question-card"&&t.type!=="blank-card").map(t=><option key={t.id} value={`tool.${t.id}`}>{t.type==="youtube"?"Open private search: ":"Trigger: "}{t.name}</option>)}{project.assets.filter(a=>!a.type.includes("audio")).map(a=><option key={key(a)} value={`background.show.${key(a)}`}>Show background: {a.name}</option>)}{project.compositions?.map(c=><option key={c.id} value={`composition.play.${c.id}`}>Play scene: {c.name}</option>)}</select></label><p>{control.detail}</p><p>Select this control to position and resize its result on the overlay. Set this action before publishing. During a game, the host presses the saved control.</p><button type="button" onClick={()=>{onChange({...project,controls:project.controls.filter(c=>c.id!==control.id)});setSelection(null);}}>Remove from dashboard</button></>}
  </section>}
 </section>;
}

