"use client";
import {useState} from 'react';
import type {GameTool,Project} from '../lib/project';
import {listCards,type ListCard} from '../lib/card-lists';
import QuestionCardEditor from './QuestionCardEditor';
export default function CardListEditor({tool,project,onSave}:{tool:GameTool;project:Project;onSave:(tool:GameTool)=>void}){
 const [name,setName]=useState(tool.name),[cards,setCards]=useState(()=>listCards(tool)),[bulk,setBulk]=useState(''),[selected,setSelected]=useState(''),[message,setMessage]=useState('');
 function save(next:ListCard[]=cards){onSave({...tool,name:name.trim()||'Card list',config:{...tool.config,cards:next}});setMessage('List and individual cards saved. Connect this list to a picker in Build Space.');}
 function compile(){const entries=bulk.split('\n').map(t=>t.trim()).filter(Boolean);if(!entries.length){setMessage('Enter at least one list item.');return;}if(cards.length+entries.length>500){setMessage('Use up to 500 cards per list.');return;}
 const seen=new Set(cards.map(c=>c.text.trim().toLocaleLowerCase()));const added=entries.filter(t=>{const key=t.toLocaleLowerCase();if(seen.has(key))return false;seen.add(key);return true;}).map(text=>({id:crypto.randomUUID(),text,design:{}}));const next=[...cards,...added];setCards(next);setBulk('');save(next);setMessage(`${added.length} individual cards created and saved. Duplicate entries were skipped.`);}
 const current=cards.find(c=>c.id===selected);
 return <section aria-label={`${tool.name} list creator`}><h3>List creator · one card per entry</h3><label>List name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Compile entries — one per line<textarea rows={6} value={bulk} onChange={e=>setBulk(e.target.value)} placeholder="Enter your movie quotes, prompts, or other list items"/></label><button type="button" onClick={compile}>Create cards from entries</button><p>Each item becomes its own saved card. Customize each card below. The picker draws these cards without repeating them during a game.</p><ol>{cards.map((card,i)=><li key={card.id}><label>Card {i+1} text<textarea value={card.text} maxLength={20000} onChange={e=>setCards(items=>items.map(c=>c.id===card.id?{...c,text:e.target.value}:c))}/></label><button type="button" onClick={()=>setSelected(card.id)}>Design card {i+1}</button><button type="button" onClick={()=>{setCards(items=>items.filter(c=>c.id!==card.id));if(selected===card.id)setSelected('');}}>Remove card {i+1} from draft</button></li>)}</ol><button type="button" onClick={()=>{if(cards.some(c=>!c.text.trim())){setMessage('Fill in each card before saving.');return;}save();}}>Save list and cards</button>{current&&<QuestionCardEditor key={current.id} project={project} tool={{id:current.id,type:'blank-card',name:`Card ${cards.findIndex(c=>c.id===current.id)+1}`,enabled:true,config:{text:current.text,questionCard:current.design}}} onSave={design=>{const next=cards.map(c=>c.id===current.id?{...c,design:design.config.questionCard as Record<string,unknown>}:c);setCards(next);save(next);}}/>}<p role="status">{message}</p></section>;
}
