"use client";
import {useState} from 'react';
import type {GameTool,Project} from '../lib/project';
import {listCards,savedListEntries,type ListCard} from '../lib/card-lists';
import QuestionCardEditor from './QuestionCardEditor';
export default function CardListEditor({tool,project,onSave}:{tool:GameTool;project:Project;onSave:(tool:GameTool)=>void}){
 const [name,setName]=useState(tool.name),[entries,setEntries]=useState(()=>savedListEntries(tool)),[cards,setCards]=useState(()=>listCards(tool)),[bulk,setBulk]=useState(''),[selected,setSelected]=useState(''),[message,setMessage]=useState('');
 function save(next:ListCard[]=cards){onSave({...tool,name:name.trim()||'Card list',config:{...tool.config,entries,cards:next}});setMessage(next.length?'Pool and cards saved.':'Pool saved. Create cards when you are ready.');}
 function compile(){const entries=bulk.split('\n').map(t=>t.trim()).filter(Boolean);if(!entries.length){setMessage('Enter at least one list item.');return;}if(cards.length+entries.length>500){setMessage('Use up to 500 cards per list.');return;}
 const seen=new Set(cards.map(c=>c.text.trim().toLocaleLowerCase()));const added=entries.filter(t=>{const key=t.toLocaleLowerCase();if(seen.has(key))return false;seen.add(key);return true;}).map(text=>({id:crypto.randomUUID(),text,design:{}}));const next=[...cards,...added];setCards(next);setBulk('');save(next);setMessage(`${added.length} individual cards created and saved. Duplicate entries were skipped.`);}
 const current=cards.find(c=>c.id===selected);
 if(current)return <section aria-label="Individual card designer"><button type="button" onClick={()=>setSelected('')}>Back to my list</button><QuestionCardEditor individual key={current.id} project={project} tool={{id:current.id,type:'blank-card',name:`Card ${cards.findIndex(c=>c.id===current.id)+1}`,enabled:true,config:{text:current.text,questionCard:current.design}}} onSave={design=>{const next=cards.map(c=>c.id===current.id?{...c,text:String(design.config.text||c.text),design:design.config.questionCard as Record<string,unknown>}:c);setCards(next);save(next);}}/><p role="status">{message}</p></section>;
 return <section className="card-editor card-host" aria-label={`${tool.name} list creator`}><h3>Pool and card designer</h3><label>List name<input value={name} onChange={e=>setName(e.target.value)}/></label>{entries.length>0&&<section aria-label="Saved pool entries"><h4>Saved pool entries</h4><p>These entries are saved in your pool. They become cards only when you choose Create cards from this pool.</p>{entries.map((entry,i)=><div key={entry.id}><label>Pool entry {i+1}<textarea value={entry.text} onChange={e=>setEntries(items=>items.map(item=>item.id===entry.id?{...item,text:e.target.value}:item))}/></label>{entry.sourceUrl&&/^https?:\/\//.test(entry.sourceUrl)&&<a href={entry.sourceUrl} target="_blank" rel="noopener noreferrer">Source: {entry.sourceTitle||'Website'}</a>}</div>)}<button type="button" onClick={()=>{const seen=new Set(cards.map(c=>c.text.trim().toLowerCase()));const added=entries.filter(e=>e.text.trim()&&!seen.has(e.text.trim().toLowerCase())).map(e=>({...e,id:crypto.randomUUID(),design:{}}));if(cards.length+added.length>500){setMessage('Use up to 500 cards per pool.');return;}const next=[...cards,...added];setCards(next);save(next);setMessage(`${added.length} cards created from your saved pool.`);}}>Create cards from this pool</button></section>}<label>Add your own card entries — one per line<textarea rows={6} value={bulk} onChange={e=>setBulk(e.target.value)} placeholder="Enter your movie quotes, prompts, or other list items"/></label><button type="button" onClick={compile}>Create cards from entries</button><p>Each item becomes its own saved card. Customize each card below. The picker draws these cards without repeating them during a game.</p><ol className="card-list-items">{cards.map((card,i)=><li key={card.id}><label>Card {i+1} text<textarea value={card.text} maxLength={20000} onChange={e=>setCards(items=>items.map(c=>c.id===card.id?{...c,text:e.target.value}:c))}/></label>{card.sourceUrl&&/^https?:\/\//.test(card.sourceUrl)&&<a href={card.sourceUrl} target="_blank" rel="noopener noreferrer">Source: {card.sourceTitle||new URL(card.sourceUrl).hostname}</a>}<button type="button" onClick={()=>setSelected(card.id)}>Design card {i+1}</button><button type="button" onClick={()=>{setCards(items=>items.filter(c=>c.id!==card.id));if(selected===card.id)setSelected('');}}>Remove card {i+1} from draft</button></li>)}</ol><button type="button" onClick={()=>{if(cards.some(c=>!c.text.trim())){setMessage('Fill in each card before saving.');return;}save();}}>{cards.length?"Save pool and cards":"Save pool"}</button><p role="status">{message}</p></section>;
}
