"use client";
import {useEditableTool} from './useEditableTool';
import {toolShapePlacement} from '../lib/overlay-placement';
import FontPicker from './FontPicker';
import {fontFamilies} from '../lib/fonts';
import CountdownDuration from "./CountdownDuration";
import {toolStyle,overlayToolPlacement} from "../lib/tool-style";
export {toolStyle,overlayToolPlacement} from "../lib/tool-style";
import { useState, type CSSProperties, type ReactNode } from "react";
import {GameEntriesEditor} from "./GameInfoTools";
import {infoTypes} from "../lib/game-tools";
import {WheelDisplay,DiceDisplay,CoinDisplay} from "./ChanceTools";
import {CountdownDesignPreview} from "./QuestionCardEditor";
import type { Project } from "../lib/project";
import type { GameTool, ProjectAsset } from "../lib/project";

const fonts=fontFamilies;
const looks=[
 {name:"Neon",backgroundColor:"#101827",textColor:"#ffffff",accentColor:"#20e8ff",fontFamily:fonts[0]},
 {name:"Light",backgroundColor:"#f4f7fb",textColor:"#182235",accentColor:"#3378bd",fontFamily:fonts[2]},
 {name:"Classic",backgroundColor:"#251a18",textColor:"#fff2d6",accentColor:"#d6aa58",fontFamily:fonts[1]},
];
export function ToolArtwork({tool,assets}:{tool:GameTool;assets:ProjectAsset[]}) {const a=(tool.config.appearance||{}) as Record<string,unknown>;const asset=assets.find(x=>(x.storageKey||x.name)===(a.imageKey||tool.config.backgroundAssetKey));return asset?.url?<img src={asset.url} alt={asset.name} style={{width:"100%",maxHeight:140,objectFit:"contain"}}/>:null;}

export default function GameToolEditor({tool,assets,onSave,project,showDuration=true}:{showDuration?:boolean;tool:GameTool;assets:ProjectAsset[];project?:Project;onSave:(next:GameTool)=>void}) {
 const {draft,commit,patchConfig,patchAppearance,patchTool}=useEditableTool(tool,onSave);const [saved,setSaved]=useState(false);const cfg=draft.config,a=(cfg.appearance||{}) as Record<string,unknown>;
 const update=(patch:Record<string,unknown>)=>{patchConfig(patch);setSaved(true)};
 const appearance=(patch:Record<string,unknown>)=>{patchAppearance(patch);setSaved(true);};
 const list=(key:string,label:string,defaults:string[]) => <label key={key}>{label}<textarea value={(Array.isArray(cfg[key])?cfg[key] as string[]:defaults).join("\n")} onChange={e=>update({[key]:e.target.value.split("\n")})}/><small>Put each choice on its own line.</small></label>;
 const images=assets.filter(x=>x.url&&(x.type.toLowerCase().includes("image")||/\.(png|jpe?g|webp|gif|svg)$/i.test(x.name)));
 let content:ReactNode=draft.name;if(draft.type==="coin-toss")content=<CoinDisplay preview faceColor={String(cfg.faceColor||"#ffd166")} textColor={String(a.textColor||"#382608")}/>;if(draft.type==="countdown")content=String(cfg.seconds??10)+" seconds";if(draft.type==="dice")content=<DiceDisplay faceColor={String(cfg.faceColor||"#f5faff")} pipColor={String(cfg.pipColor||"#102132")} result={1} sides={Number(cfg.sides)||6} preview/>;if(draft.type==="wheel")content=<WheelDisplay colors={[String(cfg.slotColor||"#154c69"),String(cfg.alternateSlotColor||"#512b75")]} textColor={String(a.textColor||"#ffffff")} entries={(Array.isArray(cfg.segments)?cfg.segments:[]).map(String)} result="" preview/>;if(draft.type==="random-picker")content="Designed cards from your saved list";if(draft.type==="poll")content=<><strong>{String(cfg.question||"Live Poll")}</strong><div>{(Array.isArray(cfg.options)?cfg.options as string[]:[]).join(" · ")}</div></>;
 if(draft.type==="random-picker")return <section className="card-editor card-host" aria-label="Random draw setup"><h4>Choose what to draw at random</h4><p>One button shows an unused item, then removes it when pressed again. Items never repeat during the same game.</p><label>Picker name<input value={draft.name} onChange={e=>{patchTool({name:e.target.value});setSaved(true);}}/></label><label>What should it draw?<select value={String(cfg.source||'cards')} onChange={e=>update({source:e.target.value})}><option value="cards">Cards from a saved list</option><option value="images">Images from an asset pool</option></select></label>{cfg.source==='images'?<label>Choose image pool<select value={String(cfg.assetPoolId||'')} onChange={e=>update({assetPoolId:e.target.value})}><option value="">Choose a pool</option>{project?.assetPools?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><small>Add images to pools in Workshop by selecting each thumbnail.</small></label>:<label>Choose card list<select value={String(cfg.listId||'')} onChange={e=>update({listId:e.target.value})}><option value="">Choose a saved card list</option>{project?.gameTools.filter(t=>t.enabled&&t.type==='card-list').map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<button type="button" className="build-btn" onClick={()=>{onSave(draft);setSaved(true);}}>Save picker</button>{saved&&<p role="status">Picker connection saved.</p>}</section>;

 const name=draft.type==="wheel"?"wheel":draft.type==="dice"?"dice":draft.type==="coin-toss"?"coin":draft.type==="poll"?"poll":draft.type==="countdown"?"timer":"tool";
 return <details className="simple-tool-editor" open={draft.type==='countdown'}><summary>Customize {draft.name}</summary><div className="simple-tool-body"><p className="tool-editor-intro">Make a few simple choices. Your preview updates and your changes save automatically.</p>
  <section className="simple-tool-section"><h4>1. Name it</h4><label>What should it be called?<input value={draft.name} onChange={e=>{patchTool({name:e.target.value});setSaved(true)}}/></label></section>
  {draft.type==='scoreboard'&&<label>What should this scoreboard count?<select value={String(cfg.scoreMode||'points')} onChange={e=>update({scoreMode:e.target.value})}><option value="points">Points</option><option value="strikes">Strikes · tally marks</option></select><small>Strikes accumulate for each team during the game. The host can add or remove one strike at a time.</small></label>}
  {infoTypes.includes(draft.type)&&<GameEntriesEditor tool={draft} project={project} onChange={entries=>update({entries})}/>}
  {(draft.type==="wheel"||draft.type==="poll")&&<section className="simple-tool-section"><h4>2. Add what it shows</h4>{draft.type==="wheel"?list("segments","Wheel choices",["Prize","Bonus"]):<><label>Poll question<input value={String(cfg.question||"")} onChange={e=>update({question:e.target.value})}/></label>{list("options","Answer choices",["Option A","Option B"])}</>}</section>}
  {draft.type==="countdown"&&<section className="simple-tool-section"><h4>2. Set up the timer</h4><label>Timer label<input value={String(cfg.label||draft.name)} onChange={e=>update({label:e.target.value})}/></label>{showDuration&&<CountdownDuration seconds={Number(cfg.seconds)||10} onSave={seconds=>{patchConfig({seconds});setSaved(true);}}/>}<label>Timer style<select value={String(cfg.display||"numbers")} onChange={e=>update({display:e.target.value})}>{[["numbers","Numbers"],["bar","Progress bar"],["circle","Circle"],["numbers-bar","Numbers and bar"],["numbers-circle","Numbers and circle"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></section>}
  {draft.type==="coin-toss"&&<p>{project?.controls.some(control=>control.action===`coin.cycle.${draft.id}`)?"This coin uses one button: first press shows it, second flips and reveals Heads or Tails, third removes it. Each step waits for the host.":"Each flip randomly chooses Heads or Tails. Connect this coin in Build Space to add its Flip and Hide buttons, or ask Build Space AI for one Show / Flip / Remove button."}</p>}
  {draft.type==="dice"&&<section className="simple-tool-section"><h4>2. Choose your dice</h4><label>Number of sides<input type="number" min={2} max={100} value={Number(cfg.sides)||6} onChange={e=>update({sides:Math.max(2,Math.min(100,+e.target.value))})}/></label></section>}
  <section className="simple-tool-section"><h4>{draft.type==="wheel"||draft.type==="poll"||draft.type==="countdown"||draft.type==="dice"?"3. Choose a look":"2. Choose a look"}</h4><p>Start with a look. You can change any color below.</p><div className="tool-look-choices">{looks.map(look=><button type="button" key={look.name} aria-pressed={a.backgroundColor===look.backgroundColor&&a.accentColor===look.accentColor} onClick={()=>appearance(look)}><span style={{background:look.backgroundColor,color:look.textColor,borderColor:look.accentColor}}>Aa</span>{look.name}</button>)}</div><label>Tool shape<select aria-label="Tool shape" value={String(a.shape||'rounded')} onChange={e=>{const shape=e.target.value;commit(current=>({...current,config:{...current.config,placement:toolShapePlacement((current.config.placement as {x:number;y:number;width:number;height:number})||{x:15,y:20,width:70,height:60},shape),appearance:{...(current.config.appearance as Record<string,unknown>||{}),shape}}}));setSaved(true);}}><option value="rectangle">Rectangle</option><option value="rounded">Rounded rectangle</option><option value="circle">Circle</option><option value="oval">Oval</option></select><small>Circle keeps equal width and height on the 1920 × 1080 overlay. Drag or resize the selected tool in Build Space.</small></label><div className="tool-look-fields">{(["backgroundColor","textColor","accentColor"] as const).map((key,i)=><label key={key}>{["Background color","Text color","Border color"][i]}<input type="color" value={String(a[key]||["#101827","#ffffff","#20e8ff"][i])} onChange={e=>appearance({[key]:e.target.value})}/></label>)}</div><FontPicker value={String(a.fontFamily||fonts[0])} onChange={fontFamily=>appearance({fontFamily})}/><label>Picture (optional)<select value={String(a.imageKey||"")} onChange={e=>appearance({imageKey:e.target.value})}><option value="">No picture</option>{images.map((x,i)=><option key={(x.storageKey||x.name)+i} value={x.storageKey||x.name}>{x.name}</option>)}</select><small>Add pictures in Workshop first, then select one here.</small></label></section>
  <section className="simple-tool-section"><h4>Preview</h4>{draft.type==="countdown"&&project?<CountdownDesignPreview project={project} tool={draft}/>:<div aria-label="Tool appearance preview" style={{...toolStyle(draft),...(a.shape==='circle'?{width:'min(100%, 240px)',aspectRatio:'1 / 1',boxSizing:'border-box'}:a.shape==='oval'?{width:'min(100%, 320px)',minHeight:160,boxSizing:'border-box'}:{})}}><ToolArtwork tool={draft} assets={assets}/><strong>{draft.name}</strong><div>{content}</div></div>}</section>
  <details className="tool-more-settings"><summary>More settings (optional)</summary><div className="tool-more-grid"><label>Text size<input type="range" min="12" max="96" value={Number(a.fontSize)||28} onChange={e=>appearance({fontSize:Number(e.target.value)})}/></label><label>Corner rounding<input type="range" min="0" max="64" value={Number(a.borderRadius??12)} onChange={e=>appearance({borderRadius:Number(e.target.value)})}/></label>{draft.type==="wheel"&&<>{["slotColor","alternateSlotColor"].map((key,i)=><label key={key}>{i?"Second wheel color":"First wheel color"}<input type="color" value={String(cfg[key]||["#154c69","#512b75"][i])} onChange={e=>update({[key]:e.target.value})}/></label>)}</>}{draft.type==="coin-toss"&&<label>Coin color<input type="color" value={String(cfg.faceColor||"#ffd166")} onChange={e=>update({faceColor:e.target.value})}/></label>}{draft.type==="dice"&&<>{["faceColor","pipColor"].map((key,i)=><label key={key}>{i?"Dice dots color":"Dice face color"}<input type="color" value={String(cfg[key]||["#f5faff","#102132"][i])} onChange={e=>update({[key]:e.target.value})}/></label>)}</>}{draft.type==="countdown"&&<>{["x","y","width","height"].map((key,i)=><label key={key}>{["Left position","Top position","Width","Height"][i]} (%)<input type="number" min="0" max="100" value={Number((cfg.placement as Record<string,number>|undefined)?.[key]??[15,78,20,12][i])} onChange={e=>update({placement:{...((cfg.placement as Record<string,number>)||{x:15,y:78,width:20,height:12}),[key]:Number(e.target.value)}})}/></label>)}</>}</div></details>
  <button type="button" className="build-btn" onClick={()=>{const clean={...draft,config:{...draft.config}};for(const key of ["segments","items","options"]){if(Array.isArray(clean.config[key]))clean.config[key]=(clean.config[key] as string[]).map(x=>x.trim()).filter(Boolean)}commit({...clean,inToolbox:tool.type!=="trivia-board"&&tool.type!=="blank-board"?true:tool.inToolbox});setSaved(true)}}>Save my {name}</button>{saved&&<p role="status">Saved. Your changes are in this project draft.</p>}
 </div></details>;
}
