"use client";
import { useState } from 'react';
import type { GameTool, Project } from '../lib/project';
import { cardDesign, questionPool } from '../lib/question-cards';
import { FittedCard, StyledTimer } from './QuestionCards';
export default function QuestionCardEditor({project,tool,onSave}:{project:Project;tool:GameTool;onSave:(tool:GameTool)=>void}){
 const [draft,setDraft]=useState(tool),[answer,setAnswer]=useState(false),[sample,setSample]=useState(''),[saved,setSaved]=useState(false);
 const key=answer?'answerCard':'questionCard',cfg=cardDesign(draft,answer);
 const update=(patch:Record<string,unknown>)=>{setSaved(false);setDraft(t=>({...t,config:{...t.config,...patch}}));};
 const design=(patch:Record<string,unknown>)=>update({[key]:{...cfg,...patch}});
 const pools=project.gameTools.filter(t=>t.type==='trivia-list'&&t.enabled),timers=project.gameTools.filter(t=>t.type==='countdown'&&t.enabled);
 const images=project.assets.filter(a=>a.url&&(a.type.toLowerCase().includes('image')||/\.(png|jpg|jpeg|webp|svg|gif)$/i.test(a.name)));
 const num=(field:string,label:string,fallback:number,min=0,max=100)=><label key={field}>{label}<input type="number" min={min} max={max} step={field.includes('Seconds')?.1:1} value={Number(cfg[field]??fallback)} onChange={e=>design({[field]:Number(e.target.value)})}/></label>;
 const question=questionPool(project,draft)[0];
 return <section className="card-editor" aria-label={`${tool.name} design and connections`}><h3>{tool.name} · design and connections</h3><label>Card system name<input value={draft.name} onChange={e=>{setDraft({...draft,name:e.target.value});setSaved(false);}}/></label>
 {draft.type==='question-card'&&<><p>Connect this once. Every random unused question uses these cards and timers.</p><div className="card-editor-fields"><label>Question pool<select value={String(draft.config.poolId||'')} onChange={e=>update({poolId:e.target.value})}><option value="">Choose saved question pool</option>{pools.map(t=><option key={t.id} value={t.id}>{t.name} · {Array.isArray(t.config.questions)?t.config.questions.length:0} questions</option>)}</select></label>{(['turnTimerId','stealTimerId'] as const).map((id,i)=><label key={id}>{i?'Steal timer':'Player Turn timer'}<select value={String(draft.config[id]||'')} onChange={e=>update({[id]:e.target.value})}><option value="">Choose countdown timer</option>{timers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>)}</div><small>Random unused questions only. Timers wait for separate host button presses. Steal completion exits the question and reveals its matching answer.</small><label>Design card<select value={answer?'answer':'question'} onChange={e=>{setAnswer(e.target.value==='answer');setSample('');}}><option value="question">Question card</option><option value="answer">Answer card</option></select></label></>}
 <div className="card-editor-fields"><label>Background image<select value={String(cfg.backgroundKey||'')} onChange={e=>design({backgroundKey:e.target.value})}><option value="">Color only</option>{images.map(a=><option key={a.storageKey||a.name} value={a.storageKey||a.name}>{a.name}</option>)}</select></label>
 <label>Font<select value={String(cfg.fontFamily||'Arial, sans-serif')} onChange={e=>design({fontFamily:e.target.value})}>{['Arial, sans-serif','Georgia, serif','Verdana, sans-serif','Trebuchet MS, sans-serif','monospace'].map(f=><option key={f} value={f}>{f.split(',')[0]}</option>)}</select></label>
 {num('fontSize','Preferred text size',48,12,160)}{['textColor','backgroundColor','accentColor','outlineColor'].map((field,i)=><label key={field}>{['Text color','Background color','Border color','Outline color'][i]}<input type="color" value={String(cfg[field]||['#ffffff','#101827','#20e8ff','#000000'][i])} onChange={e=>design({[field]:e.target.value})}/></label>)}
 <label>Text alignment<select value={String(cfg.alignment||'center')} onChange={e=>design({alignment:e.target.value})}>{['left','center','right'].map(v=><option key={v}>{v}</option>)}</select></label><label>Text position<select value={String(cfg.vertical||'center')} onChange={e=>design({vertical:e.target.value})}>{['top','center','bottom'].map(v=><option key={v}>{v}</option>)}</select></label>
 {num('outline','Text outline',0,0,5)}{num('glow','Text glow',0,0,40)}{num('borderRadius','Corner rounding',18,0,200)}{num('padding','Inner padding',28,0,100)}
 {num('width','Normal width %',65,1,100)}{num('height','Normal height %',25,1,100)}{num('x','Left position %',17.5)}{num('y','Top position %',30)}{num('marginTop','Minimum top margin %',6,0,40)}{num('marginBottom','Minimum bottom margin %',6,0,40)}{num('marginLeft','Minimum left margin %',5,0,40)}{num('marginRight','Minimum right margin %',5,0,40)}
 {(['entrance','exit'] as const).map(field=><label key={field}>{field==='entrance'?'Entrance effect':'Exit effect'}<select value={String(cfg[field]||'fade')} onChange={e=>design({[field]:e.target.value})}>{[['none','Instant'],['fade','Fade'],['left','Slide from left'],['right','Slide from right'],['top','Slide from top'],['bottom','Slide from bottom'],['zoom','Zoom / shrink'],['pop','Pop with burst']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>)}{num('entranceSeconds','Entrance seconds',.5,0,5)}{num('exitSeconds','Exit seconds',.5,0,5)}{num('delaySeconds','Entrance delay seconds',0,0,10)}</div>
 <label>Preview text<textarea value={sample} placeholder={answer?question?.answer||'Sample matching answer':question?.question||'Type a sample question to test your card'} onChange={e=>setSample(e.target.value)}/></label>
 <div className="card-design-preview" aria-label="Card live design preview"><FittedCard key={key} project={project} tool={draft} answer={answer} text={sample||String(answer?question?.answer||'Sample matching answer':question?.question||'Your question appears here')} /></div>
 <small>Each new question starts at the normal size. Longer text grows the card only as needed, within the margins. Text size reduces only when that space is full.</small>
 <button type="button" className="build-btn" onClick={()=>{onSave(draft);setSaved(true);}}>Save card design and connections</button>{saved&&<p role="status">Card design and connections saved to the draft.</p>}
 </section>;
}
export function CountdownDesignPreview({tool,project}:{tool:GameTool;project:Project}){return <div className="card-design-preview"><StyledTimer tool={{...tool,config:{...tool.config,placement:{x:25,y:25,width:50,height:50}}}} remaining={Number(tool.config.seconds)||30} total={Number(tool.config.seconds)||30}/></div>;}
