"use client";
import { useState } from 'react';
import type { Project,GameTool } from '../lib/project';
import { cardPhase, freshCardState, questionPool, timerSeconds, linkedTimer, type CardAction, type CardState } from '../lib/question-cards';
import { useCardClock } from './QuestionCards';
export default function QuestionHostPanel({project,tool,state,onCommand}:{project:Project;tool:GameTool;state?:CardState;onCommand:(id:string,action:CardAction,text?:string)=>Promise<void>|void}){
 const now=useCardClock(),current=state||freshCardState(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[text,setText]=useState(''),[reset,setReset]=useState(false);
 const phase=cardPhase(project,tool,current,now),count=questionPool(project,tool).filter(q=>!current.used.includes(q.id)).length;
 async function command(action:CardAction){if(busy)return;setError('');setBusy(true);try{await onCommand(tool.id,action,text);setReset(false);}catch(e){setError(e instanceof Error?e.message:'Card action failed.');}finally{setBusy(false);}}
 const turn=linkedTimer(project,tool),steal=linkedTimer(project,tool,true);
 const turnDone=current.turnAt!==null&&now>=current.turnAt+timerSeconds(project,tool)*1000;
 return <section className="card-host" aria-label={`${tool.name} host controls`}><h3>{tool.name}</h3>{tool.type==='blank-card'?<><label>Private blank card text<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={20000}/></label><div className="card-host-controls"><button type="button" disabled={busy||!text.trim()} onClick={()=>void command('blank')}>Show blank card</button><button type="button" disabled={busy||phase==='hidden'} onClick={()=>void command('clear')}>Hide blank card</button></div></>:<><p>{count} unused questions remain. {phase==='hidden'?'Ready to show a question.':phase==='answer'?'Matching answer is displayed.':current.stealAt!==null?'Steal timer started.':turnDone?'Player Turn finished. Start Steal when ready.':current.turnAt!==null?'Player Turn timer running.':turn?'Read the question, then start Player Turn.':'Reveal the matching answer when ready.'}</p>{current.question&&<details><summary>Private current question and answer</summary><p>{current.question.question}</p><p>Answer: {current.question.answer}</p></details>}<div className="card-host-controls"><button type="button" disabled={busy||!count||(phase!=='hidden'&&phase!=='answer')} onClick={()=>void command('show')}>Show Question</button>{turn&&<button type="button" disabled={busy||phase!=='question'||current.turnAt!==null} onClick={()=>void command('turn')}>Start Player Turn</button>}{steal&&<button type="button" disabled={busy||phase!=='question'||(!!turn&&!turnDone)||current.stealAt!==null} onClick={()=>void command('steal')}>Start Steal</button>}<button type="button" disabled={busy||phase==='hidden'||phase==='answer'} onClick={()=>void command('reveal')}>Finish question &amp; reveal answer</button><button type="button" disabled={busy||phase==='hidden'} onClick={()=>void command('clear')}>Clear card</button><button type="button" disabled={busy} onClick={()=>setReset(true)}>Start new game</button></div>{reset&&<div role="alert"><p>Start a new game and reset the used-question history?</p><button type="button" onClick={()=>void command('new-game')}>Yes, start new game</button><button type="button" onClick={()=>setReset(false)}>Keep current game</button></div>}</>}{error&&<p role="alert">{error}</p>}</section>;
}
