"use client";
import { useEffect, useRef, useState } from "react";

const steps = [
 {title:"Create your project",text:"Welcome to TTCGameLab. We’re building Neon Trivia Night together. Start a private project, name it, keep it private while you build, and describe the neon Halloween trivia experience you want.",scene:"project"},
 {title:"Generate real trivia",text:"Use the Trivia Board generator for five categories and five clues each. Real-world trivia should use factual questions and answers. Our regular test clue uses the real 1978 movie Halloween.",scene:"board"},
 {title:"Create the show assets",text:"Now make the experience yours. Generate neon board art, an original twenty-second theme song, applause, cheering, a wrong-answer sting, countdown tension, and a final celebration. Add each asset to the project and connect it to an action.",scene:"assets"},
 {title:"Build the special question",text:"Our special Halloween question asks for the origin of the jack-o’-lantern and what they were originally carved from. The generated video shows only modern pumpkin lanterns in windows, so it supports the question without giving away the answer.",scene:"special"},
 {title:"Customize the Dashboard",text:"Arrange controls around the way you host. Rename actions in language you recognize instantly. Start Show launches the theme. Big Bang can trigger a dramatic sound. Next Round can launch a transition. The labels are yours.",scene:"dashboard"},
 {title:"Run Neon Trivia Night",text:"Select a clue. The question appears and is narrated. When narration finishes, the thirty-second countdown begins. Reveal the answer, return to the board, and the used clue stays marked. That is the complete host-to-overlay loop.",scene:"live"}
] as const;

export default function TutorialPage(){
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(false),[speechOK,setSpeechOK]=useState(true),[videoMode,setVideoMode]=useState(false),[finished,setFinished]=useState(false); const utterance=useRef<SpeechSynthesisUtterance|null>(null);
 const stop=()=>{if(typeof window!=="undefined"&&"speechSynthesis" in window)window.speechSynthesis.cancel();setPlaying(false);setVideoMode(false)};
 const speak=(i:number,continuous=false)=>{if(typeof window==="undefined"||!("speechSynthesis" in window)){setSpeechOK(false);return}window.speechSynthesis.cancel();setStep(i);setFinished(false);const u=new SpeechSynthesisUtterance(steps[i].text);u.rate=.96;u.pitch=1.03;u.onend=()=>{if(continuous&&i<steps.length-1)window.setTimeout(()=>speak(i+1,true),650);else{setPlaying(false);setVideoMode(false);if(i===steps.length-1)setFinished(true)}};u.onerror=()=>{setPlaying(false);setVideoMode(false)};utterance.current=u;window.speechSynthesis.speak(u);setPlaying(true);setVideoMode(continuous)};
 useEffect(()=>()=>{if(typeof window!=="undefined"&&"speechSynthesis" in window)window.speechSynthesis.cancel()},[]); const go=(n:number)=>{stop();setFinished(false);setStep(Math.max(0,Math.min(steps.length-1,n)))}; const s=steps[step]; const progress=((step+(finished?1:0))/steps.length)*100;
 return <main style={page}><div style={{maxWidth:1120,margin:"0 auto"}}><header style={row}><div><b style={{color:"#53d8ff",letterSpacing:2}}>TTCGAMELAB TRAINER</b><h1 style={{fontSize:"clamp(36px,6vw,68px)",margin:"8px 0"}}>Neon Trivia Night</h1><p style={{color:"#bbb",fontSize:18}}>Watch the build straight through, or pause anywhere and follow along.</p></div><div style={pill}>{videoMode?"VIDEO MODE • PLAYING":`LESSON ${step+1} / ${steps.length}`}</div></header>
 <section style={player}><div style={{height:6,borderRadius:9,background:"#211d31",overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:"linear-gradient(90deg,#6c36ff,#ff7a18)",transition:"width .45s"}}/></div><div style={{display:"grid",gridTemplateColumns:"minmax(0,1.45fr) minmax(280px,.75fr)",gap:26,marginTop:26}}><Demo scene={s.scene}/><div><small style={{color:"#ff9b36",fontWeight:900}}>TRAINER NARRATION</small><h2 style={{fontSize:32,margin:"9px 0 14px"}}>{s.title}</h2><p style={{fontSize:18,lineHeight:1.65,color:"#eee"}}>{s.text}</p>{!speechOK&&<p style={{color:"#ffba78"}}>Narration is unavailable in this browser; captions remain visible.</p>}{finished&&<p style={{color:"#72f0b5",fontWeight:900}}>Tutorial complete.</p>}</div></div><div style={{...row,marginTop:26,justifyContent:"flex-start"}}><button onClick={playing?stop:()=>speak(step,true)} style={btn("#ff3f8e")}>{playing?"❚❚ Pause":"▶ Watch tutorial"}</button><button onClick={playing?stop:()=>speak(step,false)} style={btn("#713cff")}>{playing?"Stop":"Play this lesson"}</button><button onClick={()=>go(step-1)} disabled={step===0} style={btn("#22202d",step===0)}>Back</button><button onClick={()=>go(step+1)} disabled={step===steps.length-1} style={btn("#ff7a18",step===steps.length-1)}>Next →</button></div></section>
 <nav style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:9,marginTop:18}}>{steps.map((x,i)=><button key={x.title} onClick={()=>go(i)} style={{textAlign:"left",padding:13,borderRadius:13,border:i===step?"1px solid #9b72ff":"1px solid #282438",background:i===step?"#20143e":"#0c0b13",color:i===step?"white":"#999"}}><b>{i+1}</b><br/>{x.title}</button>)}</nav></div></main>
}
function Demo({scene}:{scene:typeof steps[number]["scene"]}){const shell={height:390,borderRadius:22,border:"1px solid #383052",background:"#070711",overflow:"hidden",position:"relative" as const,padding:22,boxShadow:"inset 0 0 45px rgba(80,35,170,.18)"};if(scene==="project")return <div style={shell}><Tag>AI CREATIVE PARTNER</Tag><h3>New Project</h3><Field>Neon Trivia Night</Field><div style={{...field,minHeight:100}}>Create a neon Halloween trivia game with a 5×5 board, voice narration, timer, sounds, video moments and a live host dashboard.</div><div style={{display:"flex",gap:8,marginTop:15}}><Chip>🔒 Private Project</Chip><Chip>Generate Experience ✦</Chip></div></div>;
if(scene==="board")return <div style={shell}><Tag>TRIVIA BOARD GENERATED</Tag><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:6,marginTop:16}}>{["HALLOWEEN","MOVIES","FOLKLORE","CANDY","NIGHT"].map((c,i)=><div key={c}><div style={cat}>{c}</div>{[100,200,300,400,500].map(v=><div key={v} style={tile}>${v}</div>)}</div>)}</div><p style={hint}>Real clue example: In the 1978 Halloween, what fictional Illinois town does Michael Myers return to?</p></div>;
if(scene==="assets")return <div style={shell}><Tag>ASSET COMPOSER</Tag><h3>Build the show package</h3><div style={cards}>{["🎵 20s Theme Song","👏 Applause","⚠ Wrong Sting","⏱ Countdown Tension","🎉 Final Celebration","✨ Neon Board Art"].map(x=><div style={card} key={x}>{x}<small style={{display:"block",color:"#77f0bd",marginTop:6}}>✓ Added to project</small></div>)}</div></div>;
if(scene==="special")return <div style={shell}><Tag>SPECIAL VIDEO QUESTION</Tag><div style={{height:190,borderRadius:16,background:"radial-gradient(circle,#ff8a20 0 6%,#34102e 28%,#070711 72%)",display:"grid",placeItems:"center",fontSize:58}}>🎃 🪟 🎃</div><p style={hint}>Modern jack-o’-lanterns glow in Halloween windows. The video deliberately does not show the historical answer.</p><b>Question: What is the origin of the jack-o’-lantern tradition, and what were they originally carved from?</b></div>;
if(scene==="dashboard")return <div style={shell}><Tag>HOST DASHBOARD</Tag><div style={cards}>{["▶ START SHOW","🎃 SPECIAL QUESTION","✓ SHOW ANSWER","↩ BACK TO BOARD","💥 BIG BANG","⏭ NEXT ROUND"].map(x=><div style={{...card,fontWeight:900}} key={x}>{x}</div>)}</div><p style={hint}>Customize labels so you can react instantly while live.</p></div>;
return <div style={shell}><Tag>LIVE OVERLAY</Tag><div style={{display:"grid",gridTemplateColumns:"1fr 120px",gap:15}}><div><div style={cat}>HALLOWEEN MOVIES • $200</div><div style={{...field,fontSize:22,minHeight:130,display:"grid",placeItems:"center",textAlign:"center"}}>In the original 1978 Halloween, what is the fictional Illinois town where Michael Myers returns?</div></div><div style={{...tile,fontSize:42,height:110,display:"grid",placeItems:"center"}}>30</div></div><div style={{display:"flex",gap:9,marginTop:15}}><Chip>🔊 Narration</Chip><Chip>⏱ Timer after voice</Chip><Chip>✓ Used clue saved</Chip></div></div>}
function Tag({children}:{children:React.ReactNode}){return <div style={{fontSize:12,color:"#60ddff",fontWeight:900,letterSpacing:1.5}}>{children}</div>}function Field({children}:{children:React.ReactNode}){return <div style={field}>{children}</div>}function Chip({children}:{children:React.ReactNode}){return <span style={{padding:"8px 10px",border:"1px solid #55447b",borderRadius:10,background:"#171126",fontSize:12}}>{children}</span>}
const page={minHeight:"100vh",background:"radial-gradient(circle at 18% 8%,#24104a 0,#080812 43%,#030308 100%)",color:"white",fontFamily:"system-ui,sans-serif",padding:"clamp(20px,5vw,60px)"},row={display:"flex",gap:12,alignItems:"center",justifyContent:"space-between",flexWrap:"wrap" as const},pill={border:"1px solid #704cff",borderRadius:99,padding:"9px 14px",color:"#d9cdff",fontWeight:800},player={marginTop:32,border:"1px solid #4b3475",borderRadius:28,padding:"clamp(18px,3vw,34px)",background:"rgba(12,9,28,.88)",boxShadow:"0 0 50px rgba(120,55,255,.17)"},field={padding:15,border:"1px solid #3c3356",borderRadius:12,background:"#100d19",marginTop:12,color:"#eee"},cat={padding:9,borderRadius:8,background:"#28145a",color:"#aeeeff",fontWeight:900,textAlign:"center" as const,fontSize:12},tile={padding:8,marginTop:5,borderRadius:7,background:"#101f50",color:"#ffd45a",fontWeight:900,textAlign:"center" as const},cards={display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:10,marginTop:16},card={padding:15,border:"1px solid #3c3356",borderRadius:13,background:"#12101d"},hint={color:"#aaa",fontSize:13,lineHeight:1.45};function btn(background:string,disabled=false){return {border:0,borderRadius:13,padding:"13px 18px",background:disabled?"#24232b":background,color:disabled?"#666":"white",fontWeight:900,fontSize:15,cursor:disabled?"not-allowed":"pointer"} as const}
