export const REDESIGN_OVERLAY_PROMPT = "Redesign the supplied artwork as a complete horizontal 16:9 livestream overlay for a 1920 by 1080 canvas. Recompose the actual layout: rearrange and proportionally resize the existing text blocks, characters, logos, panels and decorative elements across the whole widescreen canvas with balanced spacing and readable text. Use the original artwork as design and content reference, not as a narrow poster pasted into a wider scene. Preserve all original wording verbatim, numbers, rules, names, meaningful images, visual identity and information; do not invent, omit or repeat content. Keep all essential content within safe margins. Make the design itself occupy the full canvas. Distribute the existing content into balanced columns or a grid across the available width. For numbered lists, retain every row exactly once with its original number, label and corresponding explanation; never merge rows or drop a category. Count the source rows before arranging them. Use all panels for existing content. Do not add an empty camera window, blank game area, unused placeholder, or empty panel. Do not extend scenery at the sides, add filler panels, blank padding or black bars, stretch the original poster, or crop away any content.";

/** Animation uses a reviewed landscape design; it must not silently redesign an image. */
export async function landscapeAnimationReference(url:string):Promise<string> {
  const image=new Image();
  await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error("The animation reference could not be loaded. Try uploading the image into Workshop again."));image.src=url;});
  if(Math.abs(image.naturalWidth/image.naturalHeight-16/9)<0.02)return url;
  throw new Error("This image needs a widescreen layout before animation. In Workshop, choose Edit image → Redesign for overlay, review the new copy, then select that copy as the animation reference.");
}
